// AUTO-GENERATED by scripts/generate-curriculum-extra.mjs
import type { Subject } from "./curriculum";

export const SUBJECTS_EXTRA: Subject[] = [
  {
    "id": "ingles",
    "name": "Inglês",
    "tagline": "Hello, world!",
    "emoji": "🇬🇧",
    "colorVar": "--pt-portuguese",
    "lessons": [
      {
        "id": "en-saudacoes",
        "title": "Saudações",
        "emoji": "👋",
        "grade": 1,
        "questions": [
          {
            "prompt": "Como dizes 'Olá'?",
            "options": [
              "Bye",
              "Hello",
              "Sorry",
              "Please"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "Como dizes 'Adeus'?",
            "options": [
              "Goodbye",
              "Thanks",
              "Hello",
              "Yes"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "Como dizes 'Bom dia'?",
            "options": [
              "Good night",
              "Goodbye",
              "Hi night",
              "Good morning"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Como dizes 'Boa noite'?",
            "options": [
              "Hello",
              "Good morning",
              "Good day",
              "Good night"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Como dizes 'Por favor'?",
            "options": [
              "Yes",
              "Sorry",
              "Hello",
              "Please"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Como dizes 'Obrigado'?",
            "options": [
              "Sorry",
              "Please",
              "Yes",
              "Thank you"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Como dizes 'Desculpa'?",
            "options": [
              "Please",
              "Yes",
              "No",
              "Sorry"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Como dizes 'Sim'?",
            "options": [
              "No",
              "Yes",
              "Maybe",
              "Hi"
            ],
            "answerIndex": 1
          }
        ]
      },
      {
        "id": "en-cores",
        "title": "Cores",
        "emoji": "🎨",
        "grade": 1,
        "questions": [
          {
            "prompt": "'Red' é…",
            "options": [
              "Vermelho",
              "Amarelo",
              "Azul",
              "Verde"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Blue' é…",
            "options": [
              "Roxo",
              "Verde",
              "Azul",
              "Vermelho"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Green' é…",
            "options": [
              "Preto",
              "Azul",
              "Verde",
              "Amarelo"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Yellow' é…",
            "options": [
              "Verde",
              "Amarelo",
              "Castanho",
              "Branco"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Black' é…",
            "options": [
              "Roxo",
              "Branco",
              "Preto",
              "Cinza"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'White' é…",
            "options": [
              "Castanho",
              "Preto",
              "Branco",
              "Verde"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Orange' é…",
            "options": [
              "Roxo",
              "Laranja",
              "Castanho",
              "Rosa"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Pink' é…",
            "options": [
              "Azul",
              "Laranja",
              "Rosa",
              "Roxo"
            ],
            "answerIndex": 2
          }
        ]
      },
      {
        "id": "en-numeros",
        "title": "Números 1–10",
        "emoji": "🔢",
        "grade": 1,
        "questions": [
          {
            "prompt": "'One' é…",
            "options": [
              "1",
              "10",
              "2",
              "3"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Two' é…",
            "options": [
              "2",
              "12",
              "3",
              "4"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Three' é…",
            "options": [
              "13",
              "2",
              "3",
              "4"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Four' é…",
            "options": [
              "40",
              "5",
              "4",
              "14"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Five' é…",
            "options": [
              "50",
              "4",
              "5",
              "15"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Six' é…",
            "options": [
              "6",
              "60",
              "7",
              "16"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Seven' é…",
            "options": [
              "70",
              "6",
              "7",
              "17"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Eight' é…",
            "options": [
              "80",
              "9",
              "8",
              "18"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Nine' é…",
            "options": [
              "90",
              "8",
              "9",
              "19"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Ten' é…",
            "options": [
              "10",
              "11",
              "1",
              "100"
            ],
            "answerIndex": 0
          }
        ]
      },
      {
        "id": "en-familia",
        "title": "Família",
        "emoji": "👨‍👩‍👧",
        "grade": 2,
        "questions": [
          {
            "prompt": "'Mother' é…",
            "options": [
              "Pai",
              "Mãe",
              "Tia",
              "Avó"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Father' é…",
            "options": [
              "Mãe",
              "Pai",
              "Tio",
              "Avô"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Brother' é…",
            "options": [
              "Pai",
              "Irmão",
              "Primo",
              "Tio"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Sister' é…",
            "options": [
              "Mãe",
              "Irmã",
              "Prima",
              "Tia"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Grandmother' é…",
            "options": [
              "Mãe",
              "Tia",
              "Avó",
              "Irmã"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Grandfather' é…",
            "options": [
              "Pai",
              "Tio",
              "Avô",
              "Irmão"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Uncle' é…",
            "options": [
              "Primo",
              "Pai",
              "Tio",
              "Avô"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Aunt' é…",
            "options": [
              "Prima",
              "Mãe",
              "Tia",
              "Avó"
            ],
            "answerIndex": 2
          }
        ]
      },
      {
        "id": "en-animais",
        "title": "Animais",
        "emoji": "🐾",
        "grade": 2,
        "questions": [
          {
            "prompt": "'Cat' é…",
            "options": [
              "Gato",
              "Peixe",
              "Cão",
              "Pássaro"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Dog' é…",
            "options": [
              "Cão",
              "Vaca",
              "Gato",
              "Cavalo"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Horse' é…",
            "options": [
              "Porco",
              "Vaca",
              "Cavalo",
              "Cão"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Cow' é…",
            "options": [
              "Vaca",
              "Ovelha",
              "Cavalo",
              "Cabra"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Bird' é…",
            "options": [
              "Coelho",
              "Peixe",
              "Pássaro",
              "Rato"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Fish' é…",
            "options": [
              "Cobra",
              "Pássaro",
              "Peixe",
              "Pato"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Lion' é…",
            "options": [
              "Lobo",
              "Tigre",
              "Leão",
              "Urso"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Elephant' é…",
            "options": [
              "Elefante",
              "Rinoceronte",
              "Girafa",
              "Hipopótamo"
            ],
            "answerIndex": 0
          }
        ]
      },
      {
        "id": "en-corpo",
        "title": "Corpo",
        "emoji": "🧍",
        "grade": 3,
        "questions": [
          {
            "prompt": "'Head' é…",
            "options": [
              "Olho",
              "Mão",
              "Cabeça",
              "Pé"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Hand' é…",
            "options": [
              "Perna",
              "Pé",
              "Mão",
              "Braço"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Foot' é…",
            "options": [
              "Cabeça",
              "Mão",
              "Pé",
              "Braço"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Eye' é…",
            "options": [
              "Olho",
              "Orelha",
              "Boca",
              "Nariz"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Mouth' é…",
            "options": [
              "Dente",
              "Olho",
              "Boca",
              "Nariz"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Nose' é…",
            "options": [
              "Olho",
              "Boca",
              "Nariz",
              "Orelha"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Ear' é…",
            "options": [
              "Orelha",
              "Cabelo",
              "Olho",
              "Boca"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Hair' é…",
            "options": [
              "Pé",
              "Pele",
              "Cabelo",
              "Unhas"
            ],
            "answerIndex": 2
          }
        ]
      },
      {
        "id": "en-comida",
        "title": "Comida",
        "emoji": "🍎",
        "grade": 3,
        "questions": [
          {
            "prompt": "'Apple' é…",
            "options": [
              "Uva",
              "Pera",
              "Maçã",
              "Banana"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Bread' é…",
            "options": [
              "Arroz",
              "Bolo",
              "Pão",
              "Massa"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Milk' é…",
            "options": [
              "Chá",
              "Sumo",
              "Leite",
              "Água"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Water' é…",
            "options": [
              "Café",
              "Leite",
              "Água",
              "Sumo"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Cheese' é…",
            "options": [
              "Manteiga",
              "Queijo",
              "Pão",
              "Iogurte"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'Fish' (comida) é…",
            "options": [
              "Peixe",
              "Carne",
              "Frango",
              "Ovo"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'Rice' é…",
            "options": [
              "Trigo",
              "Massa",
              "Arroz",
              "Pão"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "'Egg' é…",
            "options": [
              "Ovo",
              "Pão",
              "Peixe",
              "Carne"
            ],
            "answerIndex": 0
          }
        ]
      },
      {
        "id": "en-verbos",
        "title": "Verbos comuns",
        "emoji": "🏃",
        "grade": 4,
        "questions": [
          {
            "prompt": "'I am' significa…",
            "options": [
              "Tu és",
              "Eu sou/estou",
              "Ele é",
              "Nós somos"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'You are' significa…",
            "options": [
              "Ele é",
              "Eles são",
              "Eu sou",
              "Tu és/Vocês são"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "'He is' significa…",
            "options": [
              "Ele é/está",
              "Ela é",
              "Eles são",
              "Eu sou"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'I have' significa…",
            "options": [
              "Eu tenho",
              "Eu vou",
              "Eu sou",
              "Eu faço"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'I go' significa…",
            "options": [
              "Eu venho",
              "Eu vou",
              "Eu fico",
              "Eu sou"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "'I like' significa…",
            "options": [
              "Eu gosto",
              "Eu vejo",
              "Eu odeio",
              "Eu vou"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'To eat' significa…",
            "options": [
              "Comer",
              "Dormir",
              "Beber",
              "Correr"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "'To drink' significa…",
            "options": [
              "Comer",
              "Saltar",
              "Falar",
              "Beber"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "'To sleep' significa…",
            "options": [
              "Acordar",
              "Comer",
              "Andar",
              "Dormir"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "'To play' significa…",
            "options": [
              "Dormir",
              "Andar",
              "Estudar",
              "Brincar/Jogar"
            ],
            "answerIndex": 3
          }
        ]
      }
    ]
  },
  {
    "id": "ciencias",
    "name": "Ciências",
    "tagline": "Descobre como tudo funciona",
    "emoji": "🔬",
    "colorVar": "--pt-math",
    "lessons": [
      {
        "id": "ci-estados",
        "title": "Estados da matéria",
        "emoji": "💧",
        "grade": 3,
        "questions": [
          {
            "prompt": "A água em estado sólido chama-se…",
            "options": [
              "Espuma",
              "Vapor",
              "Gelo",
              "Líquido"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "A água em estado gasoso chama-se…",
            "options": [
              "Sumo",
              "Gelo",
              "Vapor",
              "Líquido"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "A passagem de líquido a gás chama-se…",
            "options": [
              "Evaporação",
              "Fusão",
              "Solidificação",
              "Condensação"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "A passagem de líquido a sólido chama-se…",
            "options": [
              "Fusão",
              "Evaporação",
              "Solidificação",
              "Sublimação"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "A passagem de sólido a líquido chama-se…",
            "options": [
              "Evaporação",
              "Condensação",
              "Fusão",
              "Solidificação"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "A passagem de gás a líquido chama-se…",
            "options": [
              "Condensação",
              "Sublimação",
              "Evaporação",
              "Fusão"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "A água ferve a quantos graus?",
            "options": [
              "100",
              "0",
              "120",
              "80"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "A água congela a quantos graus?",
            "options": [
              "-10",
              "0",
              "5",
              "10"
            ],
            "answerIndex": 1
          }
        ]
      },
      {
        "id": "ci-energia",
        "title": "Energia e forças",
        "emoji": "⚡",
        "grade": 4,
        "questions": [
          {
            "prompt": "A força que nos prende ao chão é…",
            "options": [
              "Pressão",
              "Magnetismo",
              "Gravidade",
              "Atrito"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "O atrito impede que…",
            "options": [
              "O som ouça",
              "A água caia",
              "A luz passe",
              "Os corpos deslizem livremente"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "O sol é uma fonte de…",
            "options": [
              "Comida",
              "Água",
              "Som",
              "Energia"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "A eletricidade chega a casa pelos…",
            "options": [
              "Vidros",
              "Tubos",
              "Fios",
              "Canos"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Os ímans atraem objetos de…",
            "options": [
              "Plástico",
              "Vidro",
              "Ferro",
              "Madeira"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "O som propaga-se em…",
            "options": [
              "Cubos",
              "Pontos",
              "Linhas",
              "Ondas"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "A luz viaja em…",
            "options": [
              "Curvas",
              "Espirais",
              "Linha reta",
              "Quadrados"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Energia eléctrica medida em…",
            "options": [
              "Metros",
              "Graus",
              "Volts",
              "Litros"
            ],
            "answerIndex": 2
          }
        ]
      },
      {
        "id": "ci-plantas",
        "title": "Plantas",
        "emoji": "🌱",
        "grade": 2,
        "questions": [
          {
            "prompt": "Para crescer as plantas precisam de…",
            "options": [
              "Som e ar",
              "Sol e água",
              "Televisão",
              "Pilhas"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "A parte que segura a planta na terra é…",
            "options": [
              "Folha",
              "Caule",
              "Raiz",
              "Flor"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "A parte que liga raízes a folhas é…",
            "options": [
              "Flor",
              "Caule",
              "Semente",
              "Fruto"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "A reprodução começa na…",
            "options": [
              "Caule",
              "Folha",
              "Raiz",
              "Flor"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "O processo pelo qual as plantas fazem alimento é…",
            "options": [
              "Combustão",
              "Digestão",
              "Respiração",
              "Fotossíntese"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Que gás absorvem as plantas?",
            "options": [
              "Hélio",
              "Néon",
              "Dióxido de carbono",
              "Hidrogénio"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Que gás libertam as plantas?",
            "options": [
              "Azoto",
              "Hidrogénio",
              "Oxigénio",
              "Dióxido de carbono"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "A semente cresce até se tornar uma…",
            "options": [
              "Pedra",
              "Planta",
              "Nuvem",
              "Bicho"
            ],
            "answerIndex": 1
          }
        ]
      },
      {
        "id": "ci-animais",
        "title": "Classes de animais",
        "emoji": "🦁",
        "grade": 3,
        "questions": [
          {
            "prompt": "O cão é um…",
            "options": [
              "Réptil",
              "Mamífero",
              "Ave",
              "Anfíbio"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "A águia é uma…",
            "options": [
              "Ave",
              "Réptil",
              "Mamífero",
              "Peixe"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "A cobra é um…",
            "options": [
              "Réptil",
              "Ave",
              "Mamífero",
              "Anfíbio"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "O sapo é um…",
            "options": [
              "Réptil",
              "Anfíbio",
              "Peixe",
              "Mamífero"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "O salmão é um…",
            "options": [
              "Peixe",
              "Réptil",
              "Anfíbio",
              "Ave"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "A abelha é um…",
            "options": [
              "Insecto",
              "Crustáceo",
              "Aracnídeo",
              "Réptil"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "A aranha é um…",
            "options": [
              "Aracnídeo",
              "Réptil",
              "Insecto",
              "Anfíbio"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "O caranguejo é um…",
            "options": [
              "Crustáceo",
              "Peixe",
              "Insecto",
              "Réptil"
            ],
            "answerIndex": 0
          }
        ]
      },
      {
        "id": "ci-tempo",
        "title": "Tempo atmosférico",
        "emoji": "⛅",
        "grade": 2,
        "questions": [
          {
            "prompt": "Quando chove muito chama-se…",
            "options": [
              "Granizo",
              "Nevoeiro",
              "Chuva",
              "Neve"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Pequenos cristais de gelo que caem são…",
            "options": [
              "Granizo",
              "Chuva",
              "Neve",
              "Geada"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Pedaços maiores de gelo são…",
            "options": [
              "Chuva",
              "Nevoeiro",
              "Granizo",
              "Neve"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Quando o ar está cheio de gotinhas e quase não se vê é…",
            "options": [
              "Tempestade",
              "Nevoeiro",
              "Sol",
              "Vento"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "O vento é movimento de…",
            "options": [
              "Som",
              "Água",
              "Terra",
              "Ar"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "O arco-íris aparece após…",
            "options": [
              "Granizo",
              "Trovoada",
              "Neve",
              "Chuva e sol"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "O instrumento que mede temperatura é…",
            "options": [
              "Termómetro",
              "Pluviómetro",
              "Barómetro",
              "Anemómetro"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "O instrumento que mede a chuva é…",
            "options": [
              "Régua",
              "Termómetro",
              "Pluviómetro",
              "Bússola"
            ],
            "answerIndex": 2
          }
        ]
      }
    ]
  },
  {
    "id": "cidadania",
    "name": "Cidadania",
    "tagline": "Vamos viver bem juntos",
    "emoji": "🌟",
    "colorVar": "--pt-world",
    "lessons": [
      {
        "id": "cid-respeito",
        "title": "Respeito e amizade",
        "emoji": "🤝",
        "grade": 1,
        "questions": [
          {
            "prompt": "Quando alguém fala devemos…",
            "options": [
              "Sair",
              "Ignorar",
              "Ouvir",
              "Interromper"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "Pedimos as coisas dizendo…",
            "options": [
              "Quero!",
              "Toma",
              "Já!",
              "Por favor"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Quando recebemos algo dizemos…",
            "options": [
              "Mais",
              "Obrigado",
              "Olá",
              "Tchau"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "Quando erramos dizemos…",
            "options": [
              "Cala-te",
              "Não foi nada",
              "Não fui eu",
              "Desculpa"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Um bom amigo…",
            "options": [
              "Apoia e ajuda",
              "Mente",
              "Goza connosco",
              "Ignora-nos"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "Bullying é…",
            "options": [
              "Brincar com regras",
              "Magoar de propósito",
              "Dormir",
              "Estudar"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "Se vires bullying deves…",
            "options": [
              "Ignorar",
              "Rir",
              "Filmar",
              "Avisar um adulto"
            ],
            "answerIndex": 3
          }
        ]
      },
      {
        "id": "cid-ambiente",
        "title": "Cuidar do ambiente",
        "emoji": "🌍",
        "grade": 2,
        "questions": [
          {
            "prompt": "O ecoponto AMARELO é para…",
            "options": [
              "Vidro",
              "Pilhas",
              "Papel",
              "Plástico e metal"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "O ecoponto AZUL é para…",
            "options": [
              "Restos",
              "Vidro",
              "Plástico",
              "Papel e cartão"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "O ecoponto VERDE é para…",
            "options": [
              "Pilhas",
              "Papel",
              "Plástico",
              "Vidro"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Pilhas usadas vão para…",
            "options": [
              "Papelão",
              "Lixo comum",
              "Vidrão",
              "Pilhão"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Para poupar água devemos…",
            "options": [
              "Demorar mais no banho",
              "Regar de dia",
              "Lavar pratos com torneira aberta",
              "Fechar a torneira ao escovar dentes"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Para poupar luz devemos…",
            "options": [
              "Ligar tudo",
              "Deixar tudo aceso",
              "Abrir o frigorífico",
              "Apagar luzes que não usamos"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Reciclar significa…",
            "options": [
              "Reaproveitar materiais",
              "Esquecer",
              "Deitar fora",
              "Esconder"
            ],
            "answerIndex": 0
          }
        ]
      },
      {
        "id": "cid-seguranca",
        "title": "Segurança",
        "emoji": "🚦",
        "grade": 2,
        "questions": [
          {
            "prompt": "O semáforo verde para peões significa…",
            "options": [
              "Atravessar com cuidado",
              "Fugir",
              "Parar",
              "Correr"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "O semáforo vermelho significa…",
            "options": [
              "Saltar",
              "Parar",
              "Correr",
              "Andar"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "Antes de atravessar a estrada devemos…",
            "options": [
              "Olhar para os dois lados",
              "Fechar os olhos",
              "Correr",
              "Olhar para o céu"
            ],
            "answerIndex": 0
          },
          {
            "prompt": "Em caso de emergência ligamos…",
            "options": [
              "999",
              "112",
              "100",
              "115"
            ],
            "answerIndex": 1
          },
          {
            "prompt": "No carro usamos…",
            "options": [
              "Capacete",
              "Chapéu",
              "Cinto de segurança",
              "Pulseira"
            ],
            "answerIndex": 2
          },
          {
            "prompt": "De bicicleta usamos…",
            "options": [
              "Casaco",
              "Mochila",
              "Cachecol",
              "Capacete"
            ],
            "answerIndex": 3
          },
          {
            "prompt": "Não falamos com…",
            "options": [
              "Familiares",
              "Professores",
              "Estranhos",
              "Amigos"
            ],
            "answerIndex": 2
          }
        ]
      }
    ]
  }
] as Subject[];
