// curriculumBoost.ts — Lições extra (+23 lições, ~210 questões autoradas).
// São anexadas às matérias existentes em curriculum.ts — aparecem no caminho
// de aprendizagem, nas letras, nos desafios PvP e nos Desafios Expressos.
import type { Lesson, SubjectId, GradeLevel } from "@/lib/curriculum";

const L = (
  id: string,
  title: string,
  emoji: string,
  grade: GradeLevel,
  questions: Lesson["questions"],
): Lesson => ({ id, title, emoji, grade, questions });

const Q = (prompt: string, options: string[], answerIndex: number, hint?: string) => ({
  prompt,
  options,
  answerIndex,
  hint,
});

export const BOOST_LESSONS: Partial<Record<SubjectId, Lesson[]>> = {
  portugues: [
    L("boost-pt-silabas", "Caça-Sílabas Divertida", "✂️", 2, [
      Q("Quantas sílabas tem a palavra 'elefante'?", ["3", "4", "2", "5"], 0, "e-le-fan-te"),
      Q("Quantas sílabas tem 'banana'?", ["3", "4", "2", "5"], 0, "ba-na-na"),
      Q("Divide em sílabas: 'janela'.", ["ja-ne-la", "je-na-la", "jan-ela", "ja-nel-a"], 0),
      Q("Quantas sílabas tem 'computador'?", ["4", "3", "5", "2"], 0),
      Q(
        "Divide em sílabas: 'borboleta'.",
        ["bor-bo-le-ta", "borb-o-leta", "bo-rbo-leta", "bor-bo-lta"],
        0,
      ),
      Q("A palavra 'pato' tem quantas sílabas?", ["2", "1", "3", "4"], 0),
      Q("Divide em sílabas: 'escola'.", ["es-co-la", "esc-ola", "e-sco-la", "es-col-a"], 0),
      Q("Que palavra tem MAIS sílabas?", ["mariposa", "casa", "bola", "mesa"], 0),
      Q(
        "Divide em sílabas: 'cachorro'.",
        ["ca-cho-rro", "ca-cho-ro", "cach-orro", "ca-ch-orro"],
        0,
        "rr divide!",
      ),
      Q("Quantas sílabas tem 'umbrela'? (guarda-chuva em inglês)", ["4", "3", "2", "5"], 0),
    ]),
    L("boost-pt-plural", "Mundo dos Plurais", "🔢", 3, [
      Q("O plural de 'leão' é…", ["leões", "leãos", "leones", "leão"], 0),
      Q("O plural de 'avis' (pássaro) é…", ["aves", "avis", "avies", "aveses"], 0),
      Q("O plural de 'cidadão' é…", ["cidadãos", "cidadães", "cidadões", "cidadons"], 0),
      Q("O plural de 'lápis' é…", ["lápis", "lápires", "lápises", "lápia"], 0, "Não muda!"),
      Q("O plural de 'pão' é…", ["pães", "pãos", "panes", "pãoes"], 0),
      Q("O plural de 'animal' é…", ["animais", "animals", "animales", "animaes"], 0),
      Q("O plural de 'coração' é…", ["corações", "coraçãoes", "coracaos", "coraçõeses"], 0),
      Q("O plural de 'bónus' é…", ["bónus", "bónuses", "bónis", "bónues"], 0),
      Q("O plural de 'maçã' é…", ["maçãs", "maçães", "macãs", "maçans"], 0),
      Q("O plural de 'tói' (banho) é…", ["tóis", "tóes", "tois", "tóios"], 0),
    ]),
    L("boost-pt-verbos", "Aventura dos Verbos", "🏃", 3, [
      Q("Qual é o verbo nesta frase: 'O cão corre no jardim'?", ["corre", "cão", "jardim", "o"], 0),
      Q("Eu ___ (comer) uma maçã agora.", ["como", "come", "comi", "comerá"], 0),
      Q("Tu ___ (brincar) muito bem!", ["brincas", "brinca", "brinquei", "brincará"], 0),
      Q("Nós ___ (estudar) todos os dias.", ["estudamos", "estuda", "estudem", "estudou"], 0),
      Q("Passado de 'ir': Eu ___ ao mercado ontem.", ["fui", "vou", "irei", "vai"], 0),
      Q("Passado de 'ver': Eu ___ o arco-íris ontem.", ["vi", "vejo", "verei", "vejo"], 0),
      Q("Futuro de 'jogar': Amanhã eu ___ futebol.", ["jogarei", "jogo", "joguei", "jogava"], 0),
      Q("Qual é o verbo: 'A Maria canta uma canção'?", ["canta", "Maria", "canção", "uma"], 0),
      Q("Presente do verbo 'ser': Nós ___ amigos.", ["somos", "são", "é", "sois"], 0),
      Q("Presente do verbo 'estar': Eles ___ felizes.", ["estão", "está", "estou", "estás"], 0),
    ]),
    L("boost-pt-ortografia", "Ortografia Mestra", "✒️", 4, [
      Q("Qual está correta?", ["escola", "eskola", "échola", "esccola"], 0),
      Q("Completa: 'o__ar' (olhar para algo).", ["bs", "bs-…", "bserve", "observar"], 0),
      Q("Qual está correta?", ["exceção", "excessão", "esceção", "exseção"], 0),
      Q("Usa-se 'mas' ou 'mais'?: 'Quero ___ bolo.'", ["mais", "mas", "maís", "maz"], 0),
      Q("Completa: 'campeão' tem ___ antes do 'ão'.", ["e", "i", "a", "o"], 0),
      Q("Qual está correta?", ["assistir", "asistir", "assystir", "azistir"], 0),
      Q(
        "'País' leva acento porque é…",
        ["paroxítona terminada em -is", "aguda", "monossílaba", "não leva"],
        0,
      ),
      Q("Qual está correta?", ["ansioso", "anssioso", "ansiozo", "ancioso"], 0),
      Q(
        "Completa: 'inh-' (nome de fruta pequena amarela?)",
        ["ameixa", "amexa", "ameisa", "ameicha"],
        0,
      ),
      Q("Qual está correta?", ["prazer", "pracer", "prazzer", "prase"], 0),
    ]),
  ],

  matematica: [
    L("boost-mat-somar20", "Somas até 20", "➕", 1, [
      Q("7 + 5 = ?", ["12", "11", "13", "10"], 0),
      Q("9 + 8 = ?", ["17", "16", "18", "15"], 0),
      Q("6 + 6 = ?", ["12", "11", "13", "14"], 0),
      Q("8 + 9 = ?", ["17", "16", "18", "15"], 0),
      Q("10 + 10 = ?", ["20", "19", "21", "18"], 0),
      Q("11 + 4 = ?", ["15", "14", "16", "13"], 0),
      Q("13 + 7 = ?", ["20", "19", "21", "18"], 0),
      Q("5 + 7 + 2 = ?", ["14", "12", "15", "13"], 0),
      Q("12 + 8 = ?", ["20", "19", "21", "22"], 0),
      Q("Quanto é 9 + 9?", ["18", "17", "19", "16"], 0),
    ]),
    L("boost-mat-subtrair", "Subtração Mágica", "➖", 1, [
      Q("10 - 4 = ?", ["6", "5", "7", "4"], 0),
      Q("15 - 8 = ?", ["7", "6", "8", "9"], 0),
      Q("12 - 5 = ?", ["7", "6", "8", "9"], 0),
      Q("18 - 9 = ?", ["9", "8", "10", "7"], 0),
      Q("20 - 11 = ?", ["9", "8", "10", "11"], 0),
      Q("14 - 6 = ?", ["8", "7", "9", "6"], 0),
      Q("11 - 7 = ?", ["4", "3", "5", "6"], 0),
      Q("Tinhas 16 balões e rebentaram 9. Quantos ficaram?", ["7", "6", "8", "9"], 0),
      Q("17 - 8 - 3 = ?", ["6", "5", "7", "8"], 0),
      Q("9 - 9 = ?", ["0", "1", "9", "18"], 0),
    ]),
    L("boost-mat-tabuada2", "Tabuada Brilhante", "✖️", 2, [
      Q("3 × 4 = ?", ["12", "10", "14", "7"], 0),
      Q("5 × 5 = ?", ["25", "20", "30", "10"], 0),
      Q("2 × 8 = ?", ["16", "14", "18", "10"], 0),
      Q("4 × 6 = ?", ["24", "20", "28", "18"], 0),
      Q("6 × 3 = ?", ["18", "15", "21", "16"], 0),
      Q("7 × 4 = ?", ["28", "24", "32", "21"], 0),
      Q("9 × 2 = ?", ["18", "16", "20", "11"], 0),
      Q("8 × 5 = ?", ["40", "35", "45", "30"], 0),
      Q("10 × 7 = ?", ["70", "60", "77", "17"], 0),
      Q("Um pacote tem 6 lápis. Quantos lápis há em 4 pacotes?", ["24", "20", "28", "10"], 0),
    ]),
    L("boost-mat-formas", "Reino das Formas", "🔺", 2, [
      Q("Quantos lados tem um triângulo?", ["3", "4", "5", "6"], 0),
      Q("Quantos lados tem um quadrado?", ["4", "3", "5", "8"], 0),
      Q("Que forma é uma roda?", ["círculo", "quadrado", "triângulo", "retângulo"], 0),
      Q("Quantos lados tem um hexágono?", ["6", "5", "7", "8"], 0),
      Q("Uma forma com 5 lados chama-se…", ["pentágono", "hexágono", "octógono", "círculo"], 0),
      Q(
        "Qual destes não é um polígono?",
        ["círculo", "quadrado", "triângulo", "pentágono"],
        0,
        "Polígonos têm lados retos!",
      ),
      Q("Quantos vértices tem um cubo?", ["8", "6", "12", "4"], 0),
      Q("Uma bola é parecida com um…", ["esfera", "cubo", "pirâmide", "cone"], 0),
      Q("Quantos lados iguais tem um quadrado?", ["4", "2", "0", "3"], 0),
      Q(
        "Que forma tem 3 lados e 3 vértices?",
        ["triângulo", "quadrado", "círculo", "retângulo"],
        0,
      ),
    ]),
    L("boost-mat-horas", "Relógio Aventureiro", "⏰", 3, [
      Q("Quantas horas tem um dia?", ["24", "12", "30", "60"], 0),
      Q("Quantos minutos tem uma hora?", ["60", "30", "100", "24"], 0),
      Q("Quantos segundos tem um minuto?", ["60", "30", "100", "24"], 0),
      Q(
        "No ponteiro do relógio, a hora é marcada pelo ponteiro…",
        ["mais curto", "mais comprido", "vermelho", "fino"],
        0,
      ),
      Q(
        "Que horas são quando os dois ponteiros estão no 12?",
        ["12 em ponto", "6 em ponto", "3 em ponto", "meia-noite e meia"],
        0,
      ),
      Q("Quantos dias tem uma semana?", ["7", "5", "10", "30"], 0),
      Q("Quantos meses tem um ano?", ["12", "10", "24", "7"], 0),
      Q(
        "Que dia vem depois de quarta-feira?",
        ["quinta-feira", "terça-feira", "sábado", "segunda"],
        0,
      ),
      Q("Meia hora tem quantos minutos?", ["30", "15", "45", "60"], 0),
      Q(
        "A escola começa às 8h e acaba às 15h. Quantas horas ficas na escola?",
        ["7", "6", "8", "5"],
        0,
      ),
    ]),
    L("boost-mat-problemas", "Detetive de Problemas", "🧠", 4, [
      Q("Tinhas 45 meticais e gastaste 18. Quantos sobram?", ["27", "28", "26", "33"], 0),
      Q("Uma caixa tem 24 mangas. Quantas mangas há em 3 caixas?", ["72", "68", "74", "27"], 0),
      Q("A soma de dois números é 20 e um deles é 8. Qual é o outro?", ["12", "14", "10", "16"], 0),
      Q(
        "3 amigos dividem 18 doces por igual. Quantos doces cada um recebe?",
        ["6", "5", "9", "3"],
        0,
      ),
      Q(
        "Um comboio viaja 60 km por hora. Quanto viaja em 2 horas?",
        ["120 km", "100 km", "62 km", "30 km"],
        0,
      ),
      Q("Qual número é par?", ["46", "37", "51", "29"], 0),
      Q("Qual destes é múltiplo de 5?", ["35", "34", "36", "33"], 0),
      Q("Metade de 50 é…", ["25", "20", "30", "15"], 0),
      Q(
        "Um ano tem 365 dias. Quantos dias têm 2 anos (sem bissexto)?",
        ["730", "720", "700", "731"],
        0,
      ),
      Q(
        "Comprei 4 cadernos a 15 meticais cada. Paguei…",
        ["60 meticais", "45 meticais", "55 meticais", "19 meticais"],
        0,
      ),
    ]),
  ],

  "estudo-do-meio": [
    L("boost-edm-corpo", "O Meu Corpo Maravilhoso", "🫀", 1, [
      Q("Quantos olhos temos?", ["2", "1", "3", "4"], 0),
      Q("O que usamos para ouvir?", ["orelhas", "olhos", "nariz", "mãos"], 0),
      Q("Com que respiramos?", ["pulmões", "estômago", "pés", "orelhas"], 0),
      Q("O coração serve para…", ["bombear o sangue", "digerir comida", "pensar", "respirar"], 0),
      Q("Quantas mãos temos?", ["2", "1", "3", "4"], 0),
      Q("O que protege a nossa cabeça?", ["cabelo", "crânio", "couro", "chapéu"], 0),
      Q("Quantos dedos temos em cada mão?", ["5", "4", "3", "6"], 0),
      Q("Os dentes servem para…", ["mastigar", "ouvir", "cheirar", "ver"], 0),
      Q("O cérebro controla…", ["o corpo todo", "só os pés", "só as mãos", "nada"], 0),
      Q(
        "Para mantermos os dentes saudáveis devemos…",
        ["escová-los todos os dias", "comer só doces", "nunca os lavar", "bebê refrigerante"],
        0,
      ),
    ]),
    L("boost-edm-familia", "Minha Família, Meu Mundo", "👨‍👩‍👧", 2, [
      Q("O pai da minha mãe é o meu…", ["avô", "tio", "primo", "irmão"], 0),
      Q("Os filhos dos meus tios são os meus…", ["primos", "irmãos", "sobrinhos", "avós"], 0),
      Q(
        "Quem nos criou e cuida de nós em casa são…",
        ["os nossos pais/família", "estranhos", "animais", "professores só"],
        0,
      ),
      Q("A filha dos meus pais é a minha…", ["irmã", "tia", "prima", "mãe"], 0),
      Q("A mãe do meu pai é a minha…", ["avó", "tia", "irmã", "prima"], 0),
      Q("Como se chama o irmão do meu pai?", ["tio", "avô", "primo", "sobrinho"], 0),
      Q("Uma família pode ser grande ou…", ["pequena", "alta", "rápida", "nova"], 0),
      Q("Quem ensina na escola?", ["professor/professora", "polícia", "padeiro", "médico"], 0),
      Q("O bebé da minha irmã é o meu…", ["sobrinho/sobrinha", "primo", "tio", "irmão"], 0),
      Q(
        "Devemos ajudar em casa porque…",
        ["somos uma equipa", "é chato", "não há motivos", "os outros fazem tudo"],
        0,
      ),
    ]),
    L("boost-edm-natureza", "Natureza Fascinante", "🌿", 2, [
      Q(
        "As plantas precisam de quê para crescer?",
        ["sol, água e ar", "só areia", "plástico", "papel"],
        0,
      ),
      Q("As folhas são de que cor (normalmente)?", ["verde", "azul", "roxa", "preta"], 0),
      Q("As flores servem para…", ["atrair insetos e fazer sementes", "nada", "comer", "beber"], 0),
      Q("O que as raízes fazem?", ["absorvem água do solo", "voam", "cantam", "florescem"], 0),
      Q(
        "As árvores ajudam o planeta porque…",
        ["produzem oxigénio", "fazem barulho", "são bonitas só", "consomem ar"],
        0,
      ),
      Q(
        "O que acontece às folhas no outono?",
        ["caem das árvores", "ficam maiores", "viram flores", "nada"],
        0,
      ),
      Q("O que a chuva dá às plantas?", ["água", "areia", "poeira", "fogo"], 0),
      Q(
        "A semente ao germinar torna-se…",
        ["uma nova planta", "uma pedra", "um animal", "água"],
        0,
      ),
      Q(
        "As abelhas ajudam as plantas ao…",
        ["polinizar flores", "comer folhas", "partir ramos", "beber água"],
        0,
      ),
      Q(
        "Devemos cuidar da natureza porque…",
        ["é a nossa casa", "é feio", "não importa", "só animais usam"],
        0,
      ),
    ]),
    L("boost-edm-mocambique", "Orgulho de Moçambique", "🇲🇿", 3, [
      Q("Qual é a capital de Moçambique?", ["Maputo", "Beira", "Nampula", "Quelimane"], 0),
      Q("A moeda de Moçambique é o…", ["metical", "escudo", "dólar", "cwanza"], 0),
      Q(
        "Que símbolos estão na bandeira de Moçambique?",
        ["AKM, enxada, livro e estrela", "águia e cobra", "leão e coroa", "sol e lua"],
        0,
        "Simbolos de defesa, produção, educação!",
      ),
      Q("O rio mais importante de Moçambique é o…", ["Zambeze", "Nilo", "Congo", "Limpopo sul"], 0),
      Q("Uma comida tradicional moçambicana é…", ["xima", "sushi", "paella", "pizza"], 0),
      Q(
        "Quantas províncias tem Moçambique?",
        ["10", "8", "12", "11"],
        0,
        "10 + a cidade de Maputo!",
      ),
      Q("A língua oficial de Moçambique é…", ["português", "inglês", "espanhol", "swahili"], 0),
      Q("Moçambique fica em que continente?", ["África", "Ásia", "Europa", "Oceânia"], 0),
      Q("O mar que banha Moçambique é o…", ["Índico", "Atlântico", "Pacífico", "Ártico"], 0),
      Q("A ilha de Moçambique deu nome ao…", ["país", "continente", "planeta", "oceano"], 0),
    ]),
    L("boost-edm-agua", "Planeta Água", "💧", 4, [
      Q("A água no estado sólido é…", ["gelo", "vapor", "chuva", "orvalho"], 0),
      Q(
        "O ciclo da água tem chuva, evaporação e…",
        ["condensação", "combustão", "explosão", "solidificação só"],
        0,
      ),
      Q("A maior parte da Terra é coberta por…", ["água", "deserto", "floresta", "gelo"], 0),
      Q("O vapor de água sobe porque é…", ["leve", "pesado", "azul", "frio"], 0),
      Q(
        "Devemos poupar água porque…",
        ["é um bem precioso", "é barato", "sobra sempre", "não faz mal"],
        0,
      ),
      Q("A água do mar é…", ["salgada", "doce", "quente sempre", "fresca"], 0),
      Q("A água ferve a (ao nível do mar)…", ["100°C", "50°C", "150°C", "80°C"], 0),
      Q(
        "Para poupar água ao lavar os dentes devemos…",
        ["fechar a torneira", "deixar aberta", "usar a mangueira", "tomar banho com ela aberta"],
        0,
      ),
      Q("Rios desaguam no…", ["mar/lago", "céu", "sol", "deserto sempre"], 0),
      Q(
        "A chuva forma-se quando o vapor…",
        ["condensa em nuvens", "some", "vira vento", "aquece"],
        0,
      ),
    ]),
  ],

  ingles: [
    L("boost-en-colors", "Cores em Inglês", "🎨", 1, [
      Q("Como se diz 'vermelho' em inglês?", ["red", "blue", "green", "pink"], 0),
      Q("Como se diz 'azul' em inglês?", ["blue", "red", "yellow", "white"], 0),
      Q("Como se diz 'verde' em inglês?", ["green", "grey", "black", "orange"], 0),
      Q("Como se diz 'amarelo' em inglês?", ["yellow", "purple", "brown", "green"], 0),
      Q("Como se diz 'preto' em inglês?", ["black", "white", "blue", "red"], 0),
      Q("Como se diz 'branco' em inglês?", ["white", "black", "pink", "red"], 0),
      Q("Como se diz 'laranja' (cor) em inglês?", ["orange", "apple", "banana", "grape"], 0),
      Q("O céu é… (em inglês)", ["blue", "green", "red", "black"], 0),
      Q("A erva é… (em inglês)", ["green", "yellow", "purple", "white"], 0),
      Q("Como se diz 'rosa' em inglês?", ["pink", "purple", "grey", "brown"], 0),
    ]),
    L("boost-en-animals", "Animais em Inglês", "🐘", 2, [
      Q("Como se diz 'cão' em inglês?", ["dog", "cat", "bird", "cow"], 0),
      Q("Como se diz 'gato' em inglês?", ["cat", "dog", "pig", "hen"], 0),
      Q("Como se diz 'leão' em inglês?", ["lion", "bear", "wolf", "fox"], 0),
      Q("Como se diz 'peixe' em inglês?", ["fish", "bird", "frog", "snake"], 0),
      Q("Como se diz 'pássaro' em inglês?", ["bird", "fish", "cat", "dog"], 0),
      Q("Como se diz 'vaca' em inglês?", ["cow", "sheep", "goat", "horse"], 0),
      Q("Como se diz 'elefante' em inglês?", ["elephant", "giraffe", "zebra", "monkey"], 0),
      Q("Como se diz 'macaco' em inglês?", ["monkey", "donkey", "rabbit", "mouse"], 0),
      Q("The elephant is… (grande)", ["big", "small", "fast", "red"], 0),
      Q("Como se diz 'rato' em inglês?", ["mouse", "horse", "house", "moth"], 0),
    ]),
    L("boost-en-numbers", "Números em Inglês", "🔢", 2, [
      Q("Como se escreve '3' em inglês?", ["three", "tree", "ten", "two"], 0),
      Q("Como se escreve '7' em inglês?", ["seven", "six", "eight", "eleven"], 0),
      Q("Como se escreve '10' em inglês?", ["ten", "two", "twelve", "twenty"], 0),
      Q("Como se escreve '5' em inglês?", ["five", "four", "nine", "fivehundred"], 0),
      Q("How many legs do you have? (Quantas pernas tens?)", ["two", "ten", "five", "six"], 0),
      Q("Como se escreve '1' em inglês?", ["one", "won", "nine", "onee"], 0),
      Q("'Nine' é o número…", ["9", "10", "8", "11"], 0),
      Q("Como se escreve '20' em inglês?", ["twenty", "twelve", "ten", "two"], 0),
      Q("'Eight' é o número…", ["8", "9", "7", "10"], 0),
      Q("2 + 2 = ? (em inglês)", ["four", "for", "five", "free"], 0),
    ]),
    L("boost-en-greetings", "Cumprimentos em Inglês", "👋", 3, [
      Q("'Good morning' quer dizer…", ["bom dia", "boa noite", "adeus", "obrigado"], 0),
      Q("'Good night' quer dizer…", ["boa noite", "bom dia", "boa tarde", "até já"], 0),
      Q(
        "'How are you?' quer dizer…",
        ["como estás?", "quem és?", "onde vais?", "quantos anos tens?"],
        0,
      ),
      Q(
        "A resposta a 'How are you?' pode ser…",
        ["I'm fine, thank you!", "My name is...", "Two!", "Red!"],
        0,
      ),
      Q("'Please' quer dizer…", ["por favor", "obrigado", "desculpa", "adeus"], 0),
      Q("'Thank you' quer dizer…", ["obrigado", "por favor", "bom dia", "não"], 0),
      Q("'Goodbye' quer dizer…", ["adeus", "olá", "sim", "por favor"], 0),
      Q(
        "'What is your name?' quer dizer…",
        ["como te chamas?", "quantos anos tens?", "onde moras?", "como estás?"],
        0,
      ),
      Q(
        "A resposta a 'What is your name?' é…",
        ["My name is Ana", "I am fine", "I am seven", "Good night"],
        0,
      ),
      Q("'You're welcome' responde a…", ["thank you", "hello", "goodbye", "sorry"], 0),
    ]),
  ],

  ciencias: [
    L("boost-cie-animais", "Cientista dos Animais", "🔬", 1, [
      Q("As vacas comem…", ["erva/capim", "carne", "peixe", "pão"], 0),
      Q("Os peixes respiram por…", ["guelras", "pulmões", "nariz", "pele"], 0),
      Q("Os pássaros têm…", ["penas", "pêlo", "escamas", "conchas"], 0),
      Q("Que animal põe ovos?", ["galinha", "vaca", "cão", "gato"], 0),
      Q("Os leões vivem em…", ["manadas (grupos)", "casas", "água", "árvores"], 0),
      Q("O que os gatos adoram beber?", ["leite", "sumo", "refrigerante", "café"], 0),
      Q(
        "As borboletas nascem de…",
        ["lagartas (crisálida)", "ovos de pássaro", "sementes", "pedras"],
        0,
      ),
      Q("Que animal anda devagar e carrega a casa?", ["caracol", "coelho", "leão", "cavalo"], 0),
      Q("Os sapos vivem perto de…", ["água", "deserto", "montanha", "cidade"], 0),
      Q("Que animal é nosso amigo e guarda a casa?", ["cão", "leão", "tigre", "lobo"], 0),
    ]),
    L("boost-cie-plantas", "Laboratório das Plantas", "🌱", 3, [
      Q(
        "A parte da planta que fica debaixo da terra é…",
        ["a raiz", "a flor", "a folha", "o caule"],
        0,
      ),
      Q("A fotossíntese usa a luz do…", ["sol", "lua", "fogão", "frigorífico"], 0),
      Q("As plantas libertam que gás importante?", ["oxigénio", "fumo", "hélio", "metano"], 0),
      Q("O caule serve para…", ["sustentar a planta", "cheirar", "voar", "cavar"], 0),
      Q(
        "As plantas com flores atraem…",
        ["insetos polinizadores", "pedras", "carros", "nuvens"],
        0,
      ),
      Q("Uma planta carnívora come…", ["insetos", "carne de vaca", "arroz", "pão"], 0),
      Q("Os cactos guardam…", ["água", "areia", "pedras", "ar"], 0),
      Q(
        "As árvores vivem quantos anos (algumas)?",
        ["centenas", "um dia", "uma hora", "um mês"],
        0,
      ),
      Q(
        "Para crescer, uma semente precisa de…",
        ["água e terra", "plástico", "vento só", "luz da lua só"],
        0,
      ),
      Q("O que não é uma planta?", ["pedra", "roseira", "girassol", "samambaia"], 0),
    ]),
  ],

  cidadania: [
    L("boost-cid-emocoes", "Emoções Felizes", "😊", 1, [
      Q("Quando ganhas um jogo sentes-te…", ["feliz", "triste", "com sono", "com medo"], 0),
      Q(
        "Quando perdes algo importante podes sentir-te…",
        ["triste", "alegre", "com fome", "irritado só"],
        0,
      ),
      Q(
        "Se um amigo está triste podes…",
        ["consolar e brincar com ele", "rir dele", "ignorar sempre", "bater-lhe"],
        0,
      ),
      Q("Quando algo nos assusta sentimos…", ["medo", "alegria", "fome", "orgulho"], 0),
      Q("Pedir desculpa mostra que somos…", ["corajosos e honestos", "fracos", "bobos", "maus"], 0),
      Q(
        "Quando alguém fala, devemos…",
        ["escutar com atenção", "interromper", "fugir", "gritar"],
        0,
      ),
      Q("Compartilhar os brinquedos é…", ["generoso", "proibido", "mau", "engraçado"], 0),
      Q("Dizer 'obrigado' mostra…", ["gratidão", "raiva", "medo", "vergonha"], 0),
      Q(
        "Se sentes raiva, o melhor é…",
        ["respirar fundo e falar", "bater", "gritar sem parar", "quebrar coisas"],
        0,
      ),
      Q(
        "Cada pessoa tem emoções que são…",
        ["normais e importantes", "bobas", "proibidas", "iguais sempre"],
        0,
      ),
    ]),
    L("boost-cid-ambiente", "Guardiões do Planeta", "🌍", 3, [
      Q(
        "Para ajudar o planeta devemos…",
        ["reciclar", "queimar lixo", "poluir rios", "cortar árvores"],
        0,
      ),
      Q("O lixo deve ir para…", ["o lixo/reciclagem", "o chão", "o mar", "o rio"], 0),
      Q(
        "Guardar papel para reciclar ajuda…",
        ["as árvores", "os carros", "as nuvens", "o vento"],
        0,
      ),
      Q("Ecopontos são locais para…", ["depositar reciclagem", "brincar", "dormir", "comer"], 0),
      Q(
        "Não poluir o ar significa…",
        ["andar a pé ou de bicicleta", "queimar plásticos", "usar fogo sempre", "fumar"],
        0,
      ),
      Q(
        "Os plásticos no mar fazem mal…",
        ["aos animais marinhos", "a nada", "só às pedras", "às nuvens"],
        0,
      ),
      Q(
        "Plantar árvores ajuda porque…",
        ["limpam o ar", "fazem som só", "ocupam espaço", "custam dinheiro"],
        0,
      ),
      Q("Apagar a luz ao sair poupa…", ["energia", "água", "papel", "comida"], 0),
      Q("Fechar a torneira poupa…", ["água", "energia elétrica só", "papel", "ar"], 0),
      Q(
        "Cuidar do planeta é trabalho de…",
        ["todos nós", "só os pais", "só os professores", "só o governo"],
        0,
      ),
    ]),
  ],
};
