// triviaBoost.ts — Banco de trivia adicional (+130 questões autoradas).
// Categorias espelhadas no triviaBank.ts; merged em ALL_TRIVIA.
export interface TriviaQuestion {
  category: string;
  age: number;
  prompt: string;
  options: string[];
  answerIndex: number;
  hint?: string;
}

export const TRIVIA_BOOST: TriviaQuestion[] = [
  // ─── Animais (20) ───
  {
    category: "animais",
    age: 7,
    prompt: "Qual é o maior felino do mundo?",
    options: ["Leão", "Tigre", "Leopardo", "Onça-pintada"],
    answerIndex: 1,
  },
  {
    category: "animais",
    age: 6,
    prompt: "Que animal tem uma tromba?",
    options: ["Rinoceronte", "Hipopótamo", "Elefante", "Búfalo"],
    answerIndex: 2,
  },
  {
    category: "animais",
    age: 7,
    prompt: "Como se chama o bebé do cão?",
    options: ["Potro", "Cachorro", "Cabrito", "Cordeiro"],
    answerIndex: 1,
  },
  {
    category: "animais",
    age: 6,
    prompt: "Qual destes animais voa?",
    options: ["Morcego", "Pinguim", "Mosquito-da-areia", "Ouriço"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 8,
    prompt: "A aranha não é um inseto porque tem…",
    options: ["8 patas", "6 patas", "asas", "pelo"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 7,
    prompt: "Que animal é famoso por mudar de cor?",
    options: ["Camaleão", "Tartaruga", "Rinoceronte", "Panda"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 6,
    prompt: "O cavalo bebé chama-se…",
    options: ["Potro", "Borrego", "Leitão", "Gato"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 8,
    prompt: "Qual é o peixe mais venenoso do mundo?",
    options: ["Peixe-balão", "Sardinha", "Salmão", "Atum"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 6,
    prompt: "Que animal faz 'muuu'?",
    options: ["Ovelha", "Vaca", "Cabra", "Porco"],
    answerIndex: 1,
  },
  {
    category: "animais",
    age: 7,
    prompt: "As abelhas fazem quê?",
    options: ["Mel", "Leite", "Seda", "Melão"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 7,
    prompt: "O caracol anda sobre…",
    options: ["um pé", "duas pernas", "quatro patas", "asas"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 8,
    prompt: "Que ave não consegue voar?",
    options: ["Águia", "Papagaio", "Avestruz", "Andorinha"],
    answerIndex: 2,
  },
  {
    category: "animais",
    age: 6,
    prompt: "Quantas pernas tem um insecto?",
    options: ["4", "6", "8", "10"],
    answerIndex: 1,
  },
  {
    category: "animais",
    age: 8,
    prompt: "O crocodilo é um…",
    options: ["anfíbio", "réptil", "mamífero", "ave"],
    answerIndex: 1,
  },
  {
    category: "animais",
    age: 7,
    prompt: "Que animal dorme de pé?",
    options: ["Cavalo", "Gato", "Cão", "Rato"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 6,
    prompt: "A ovelha dá-nos…",
    options: ["lã", "couro", "seda", "algodão"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 8,
    prompt: "O maior animal terrestre é…",
    options: ["elefante-africano", "girafa", "hipopótamo", "rinoceronte"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 7,
    prompt: "Que animal tem espinhos no corpo?",
    options: ["Ouriço", "Coelho", "Raposa", "Lontra"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 6,
    prompt: "O pato vive perto de…",
    options: ["água", "deserto", "montanha", "cueca"],
    answerIndex: 0,
  },
  {
    category: "animais",
    age: 9,
    prompt: "Como se chama o estudo dos animais?",
    options: ["Zoologia", "Botânica", "Geologia", "Astronomia"],
    answerIndex: 0,
  },

  // ─── Espaço (15) ───
  {
    category: "espaco",
    age: 7,
    prompt: "Qual é o planeta mais próximo do Sol?",
    options: ["Vénus", "Mercúrio", "Marte", "Terra"],
    answerIndex: 1,
  },
  {
    category: "espaco",
    age: 7,
    prompt: "Quantos planetas tem o Sistema Solar?",
    options: ["7", "8", "9", "10"],
    answerIndex: 1,
  },
  {
    category: "espaco",
    age: 8,
    prompt: "Qual é o planeta vermelho?",
    options: ["Júpiter", "Saturno", "Marte", "Neptuno"],
    answerIndex: 2,
  },
  {
    category: "espaco",
    age: 6,
    prompt: "A luz do Sol demora cerca de ___ a chegar à Terra.",
    options: ["8 minutos", "8 segundos", "8 horas", "8 dias"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 8,
    prompt: "Qual é a estrela mais próxima da Terra?",
    options: ["Sirius", "Sol", "Polar", "Alpha Centauri"],
    answerIndex: 1,
  },
  {
    category: "espaco",
    age: 9,
    prompt: "Que planeta é famoso pelos seus anéis?",
    options: ["Saturno", "Marte", "Mercúrio", "Vénus"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 8,
    prompt: "Como se chama a galáxia onde vivemos?",
    options: ["Via Láctea", "Andrómeda", "Órion", "Big Bang"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 7,
    prompt: "Quem foi o primeiro homem no espaço?",
    options: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Galileu"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 8,
    prompt: "O que é um cometa?",
    options: ["bola de gelo e poeira", "estrela morta", "planeta pequeno", "lua"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 7,
    prompt: "A Lua gira em volta de…",
    options: ["da Terra", "do Sol", "de Marte", "de Vénus"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 9,
    prompt: "Qual é o maior planeta do Sistema Solar?",
    options: ["Júpiter", "Saturno", "Netuno", "Terra"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 8,
    prompt: "O telescópio serve para…",
    options: ["ver o céu", "ouvir sons", "medir temperatura", "ver bactérias"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 7,
    prompt: "Astronautas comem no espaço comida…",
    options: ["especial", "congelada só", "queimada", "verde"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 9,
    prompt: "O que é a Via Láctea?",
    options: ["uma galáxia", "um planeta", "um satélite", "uma nave"],
    answerIndex: 0,
  },
  {
    category: "espaco",
    age: 8,
    prompt: "Em que planeta há evidência de água congelada?",
    options: ["Marte", "Mercúrio", "Vénus", "Júpiter"],
    answerIndex: 0,
  },

  // ─── Corpo (12) ───
  {
    category: "corpo",
    age: 6,
    prompt: "Com que órgão ouvimos?",
    options: ["orelhas", "nariz", "olhos", "boca"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 7,
    prompt: "Quantos dentes tem uma criança (dentes de leite)?",
    options: ["20", "32", "16", "28"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 7,
    prompt: "O que protege o cérebro?",
    options: ["o crânio", "as costelas", "a pele", "os joelhos"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 6,
    prompt: "Quantos olhos temos?",
    options: ["2", "1", "3", "4"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 8,
    prompt: "O coração é do tamanho de…",
    options: ["um punho", "uma bola de futebol", "uma cabeça", "um dedo"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 7,
    prompt: "Com o que respiramos?",
    options: ["pulmões", "estômago", "fígado", "rins"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 8,
    prompt: "Quantos dedos têm as duas mãos juntas?",
    options: ["10", "8", "12", "20"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 6,
    prompt: "O cabelo cresce no…",
    options: ["couro cabeludo", "cotovelo", "joelho", "ouvido externo"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 8,
    prompt: "Qual é o músculo mais forte do corpo?",
    options: ["a língua", "bíceps", "gémeos", "trapézio"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 7,
    prompt: "A pele serve para…",
    options: ["proteger o corpo", "dizer horas", "digerir comida", "respirar só"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 6,
    prompt: "Com que parte do corpo vemos?",
    options: ["olhos", "orelhas", "nariz", "mãos"],
    answerIndex: 0,
  },
  {
    category: "corpo",
    age: 9,
    prompt: "O que fazem os rins?",
    options: ["filtram o sangue", "bombear sangue", "digerir", "pensar"],
    answerIndex: 0,
  },

  // ─── Ciência (15) ───
  {
    category: "ciencia",
    age: 7,
    prompt: "O gelo é água…",
    options: ["congelada", "a ferver", "quente", "doce"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 8,
    prompt: "O que atrai o ferro?",
    options: ["ímã", "madeira", "vidro", "plástico"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 7,
    prompt: "O arco-íris tem quantas cores?",
    options: ["7", "5", "6", "8"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 8,
    prompt: "O que é a evaporação?",
    options: ["líquido vira gás", "gás vira líquido", "sólido vira líquido", "água congela"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 6,
    prompt: "Que instrumento usamos para ver muito pequeno?",
    options: ["microscópio", "telescópio", "binóculos", "lupa grande"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 8,
    prompt: "O som viaja mais depressa no…",
    options: ["água", "vácuo", "madeira", "nada"],
    answerIndex: 2,
  },
  {
    category: "ciencia",
    age: 7,
    prompt: "A eletricidade das casas vem da…",
    options: ["tomada", "torneira", "chaminé", "janela"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 9,
    prompt: "Que gás libertamos ao respirar?",
    options: ["dióxido de carbono", "oxigénio", "hélio", "azoto puro"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 8,
    prompt: "Um vulcão lança…",
    options: ["lava", "água doce", "areia só", "gelo"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 7,
    prompt: "A chuva forma-se de…",
    options: ["nuvens", "estrelas", "poeira só", "vento"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 8,
    prompt: "O que é mais leve?",
    options: ["uma pena", "um tijolo", "um livro", "uma pedra"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 9,
    prompt: "Como se chama o derretimento do gelo?",
    options: ["fusão", "evaporação", "condensação", "sublimação"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 6,
    prompt: "Que cor se forma ao misturar azul e amarelo?",
    options: ["verde", "roxo", "laranja", "castanho"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 8,
    prompt: "Os fósseis são restos de…",
    options: ["seres muito antigos", "plásticos", "comida fresca", "carros"],
    answerIndex: 0,
  },
  {
    category: "ciencia",
    age: 7,
    prompt: "O que usamos para medir a temperatura?",
    options: ["termómetro", "régua", "relógio", "balança"],
    answerIndex: 0,
  },

  // ─── Mundo (15) ───
  {
    category: "mundo",
    age: 8,
    prompt: "Qual é o maior país do mundo?",
    options: ["Rússia", "China", "Canadá", "Brasil"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 7,
    prompt: "Em que continente está o Brasil?",
    options: ["América do Sul", "África", "Europa", "Ásia"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 8,
    prompt: "A Torre Eiffel fica em…",
    options: ["Paris", "Londres", "Roma", "Madrid"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 7,
    prompt: "Que continente é o mais frio?",
    options: ["Antártida", "África", "Ásia", "Europa"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 8,
    prompt: "A Grande Muralha fica em…",
    options: ["China", "Japão", "Índia", "Coreia"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 9,
    prompt: "Qual é o deserto mais extenso do mundo?",
    options: ["Antártico (deserto polar)", "Sahara", "Gobi", "Kalahari"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 7,
    prompt: "O Egipto é famoso pelas…",
    options: ["pirâmides", "montanhas nevadas", "geysers", "fiordes"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 8,
    prompt: "Quantas cores tem a bandeira de Moçambique?",
    options: ["4", "5", "6", "3"],
    answerIndex: 1,
  },
  {
    category: "mundo",
    age: 7,
    prompt: "Qual destes países fala português?",
    options: ["Angola", "Nigéria", "Quénia", "Gana"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 8,
    prompt: "O Everest fica nos…",
    options: ["Himalaias", "Andes", "Alpes", "Atlas"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 9,
    prompt: "Qual é a cidade mais populosa do Brasil?",
    options: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 7,
    prompt: "Como se chama a casa do esquimó?",
    options: ["iglu", "tenda", "palhota", "rulote"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 8,
    prompt: "O Niagara é umas…",
    options: ["cataratas", "montanhas", "florestas", "cidades"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 7,
    prompt: "O mapa serve para…",
    options: ["encontrar caminhos", "cozinhar", "dormir", "cantar"],
    answerIndex: 0,
  },
  {
    category: "mundo",
    age: 9,
    prompt: "Que oceano fica entre África e Austrália?",
    options: ["Índico", "Atlântico", "Pacífico", "Ártico"],
    answerIndex: 0,
  },

  // ─── Português (15) ───
  {
    category: "portugues",
    age: 7,
    prompt: "Quantas sílabas tem 'borboleta'?",
    options: ["4", "3", "5", "2"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 7,
    prompt: "O plural de 'flor' é…",
    options: ["flores", "flors", "floreses", "flor"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 6,
    prompt: "Qual palavra rima com 'gato'?",
    options: ["pato", "cão", "vaca", "leão"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 8,
    prompt: "Um nome de pessoa, lugar ou coisa chama-se…",
    options: ["substantivo", "verbo", "adjetivo", "advérbio"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 7,
    prompt: "Qual é a primeira letra do alfabeto?",
    options: ["A", "B", "Z", "M"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 6,
    prompt: "Quantas vogais temos?",
    options: ["5", "3", "7", "6"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 8,
    prompt: "O oposto de 'claro' é…",
    options: ["escuro", "brilhante", "branco", "azul"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 7,
    prompt: "'Coração' começa por…",
    options: ["C", "G", "S", "K"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 8,
    prompt: "Qual palavra está escrita corretamente?",
    options: ["escola", "eskola", "échola", "escolla"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 6,
    prompt: "Quantas letras tem 'sol'?",
    options: ["3", "4", "5", "2"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 8,
    prompt: "Uma palavra com significado parecido é um…",
    options: ["sinónimo", "antónimo", "homónimo", "acronymo"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 7,
    prompt: "Qual é a última letra do alfabeto?",
    options: ["Z", "A", "M", "R"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 8,
    prompt: "'Correr', 'saltar' e 'nadar' são…",
    options: ["verbos", "nomes", "adjetivos", "letras"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 7,
    prompt: "Como se chama a palavra que descreve (bonito, alto)?",
    options: ["adjetivo", "verbo", "substantivo", "número"],
    answerIndex: 0,
  },
  {
    category: "portugues",
    age: 9,
    prompt: "Qual frase está correta?",
    options: ["Há muitos livros.", "A muitos livros.", "Á muitos livros.", "As muitos livros."],
    answerIndex: 0,
  },

  // ─── Desporto (8) ───
  {
    category: "desporto",
    age: 7,
    prompt: "Quantos jogadores tem uma equipa de futebol em campo?",
    options: ["11", "10", "12", "9"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 8,
    prompt: "A que altura fica o cesto de basquetebol?",
    options: ["3,05 m", "2,50 m", "4 m", "3,50 m"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 7,
    prompt: "O que se faz no desporto natação?",
    options: ["nadar", "correr", "saltar", "pedalar"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 8,
    prompt: "Quantos pontos vale um golo no futebol?",
    options: ["1", "2", "3", "5"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 7,
    prompt: "Que desporto usa uma raquete?",
    options: ["ténis", "futebol", "natação", "atletismo"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 9,
    prompt: "De quanto em quanto tempo são os Jogos Olímpicos?",
    options: ["4 anos", "2 anos", "5 anos", "todos os anos"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 7,
    prompt: "Em que desporto se usa uma bicicleta?",
    options: ["ciclismo", "boxe", "judô", "remo"],
    answerIndex: 0,
  },
  {
    category: "desporto",
    age: 8,
    prompt: "Quantos tempos tem um jogo de basquetebol?",
    options: ["4", "2", "3", "5"],
    answerIndex: 0,
  },

  // ─── Arte (6) ───
  {
    category: "arte",
    age: 7,
    prompt: "Com que pintamos?",
    options: ["tinta", "terra", "água só", "areia"],
    answerIndex: 0,
  },
  {
    category: "arte",
    age: 8,
    prompt: "Quem pintou a Mona Lisa?",
    options: ["Leonardo da Vinci", "Picasso", "Van Gogh", "Dalí"],
    answerIndex: 0,
  },
  {
    category: "arte",
    age: 6,
    prompt: "Que cor se faz com vermelho e branco?",
    options: ["rosa", "roxo", "azul", "verde"],
    answerIndex: 0,
  },
  {
    category: "arte",
    age: 7,
    prompt: "Onde guardamos quadros famosos?",
    options: ["museus", "cozinhas", "garagens", "fábricas"],
    answerIndex: 0,
  },
  {
    category: "arte",
    age: 8,
    prompt: "Esculpir é trabalhar com…",
    options: ["pedra ou madeira", "papel só", "água", "vento"],
    answerIndex: 0,
  },
  {
    category: "arte",
    age: 7,
    prompt: "Que instrumento serve para desenhar linhas retas?",
    options: ["régua", "tesoura", "cola", "borracha"],
    answerIndex: 0,
  },

  // ─── Música (8) ───
  {
    category: "musica",
    age: 7,
    prompt: "Quantas notas musicais existem?",
    options: ["7", "5", "8", "10"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 6,
    prompt: "Qual é a nota depois de 'dó'?",
    options: ["ré", "fá", "si", "lá"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 7,
    prompt: "O piano tem…",
    options: ["teclas", "cordas só", "palhetas", "tubos"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 8,
    prompt: "Quem toca a bateria faz…",
    options: ["ritmo", "melodia", "letra", "cena"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 7,
    prompt: "A guitarra tem quantas cordas (normal)?",
    options: ["6", "4", "8", "10"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 6,
    prompt: "O que usamos para ouvir música?",
    options: ["orelhas", "pés", "mãos", "cabelo"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 8,
    prompt: "Uma pessoa que canta é um…",
    options: ["cantor", "pintor", "dançarino", "escritor"],
    answerIndex: 0,
  },
  {
    category: "musica",
    age: 7,
    prompt: "O violino toca-se com…",
    options: ["arco", "baquetas", "dedos só", "sopros"],
    answerIndex: 0,
  },

  // ─── Portugal (8) ───
  {
    category: "portugal",
    age: 7,
    prompt: "A capital de Portugal é…",
    options: ["Lisboa", "Porto", "Faro", "Braga"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 8,
    prompt: "Que doce português é famoso?",
    options: ["pastel de nata", "sushi", "taco", "croissant"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 7,
    prompt: "A bandeira de Portugal tem que cores principais?",
    options: ["verde e vermelho", "azul e branco", "amarelo e verde", "roxo e branco"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 8,
    prompt: "O rio mais longo de Portugal é o…",
    options: ["Tejo", "Douro", "Mondego", "Sado"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 7,
    prompt: "Portugal fica em que continente?",
    options: ["Europa", "Ásia", "África", "América"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 8,
    prompt: "O Porto é famoso pelo…",
    options: ["vinho do Porto", "samba", "tango", "flamenco"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 7,
    prompt: "O mar que banha Portugal é o…",
    options: ["Atlântico", "Pacífico", "Índico", "Ártico"],
    answerIndex: 0,
  },
  {
    category: "portugal",
    age: 9,
    prompt: "A língua oficial de Portugal é…",
    options: ["português", "espanhol", "francês", "inglês"],
    answerIndex: 0,
  },

  // ─── Inglês (8) ───
  {
    category: "ingles",
    age: 7,
    prompt: "Como se diz 'gato' em inglês?",
    options: ["cat", "dog", "bird", "fish"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 7,
    prompt: "Como se diz 'vermelho' em inglês?",
    options: ["red", "blue", "green", "yellow"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 8,
    prompt: "Como se escreve o número 5 em inglês?",
    options: ["five", "four", "six", "ten"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 6,
    prompt: "'Hello' quer dizer…",
    options: ["olá", "adeus", "obrigado", "por favor"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 7,
    prompt: "Como se diz 'árvore' em inglês?",
    options: ["tree", "flower", "grass", "leaf"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 8,
    prompt: "Como se diz 'professor' em inglês?",
    options: ["teacher", "doctor", "farmer", "pilot"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 7,
    prompt: "'Thank you' quer dizer…",
    options: ["obrigado", "desculpa", "adeus", "sim"],
    answerIndex: 0,
  },
  {
    category: "ingles",
    age: 8,
    prompt: "Como se diz 'cão' em inglês?",
    options: ["dog", "cat", "cow", "pig"],
    answerIndex: 0,
  },
];

/** Banco total: triviaBank (auto-gerado) + boost autorado. */
import { TRIVIA_BANK } from "@/lib/triviaBank";
export const ALL_TRIVIA: TriviaQuestion[] = [...TRIVIA_BANK, ...TRIVIA_BOOST];

/** Escolhe n perguntas aleatórias do banco total, opcionalmente por categoria. */
export function getRandomTriviaBoost(n: number, category?: string): TriviaQuestion[] {
  const pool = category ? ALL_TRIVIA.filter((q) => q.category === category) : ALL_TRIVIA;
  return [...pool].sort(() => Math.random() - 0.5).slice(0, n);
}
