// triviaUltra.ts — Mega-expansão de trivia (+320 questões autoradas, Ronda 2).
// Categorias novas: espaço, corpo, música, inventores, moçambique, lógica,
// plantas, oceano, profissões, desporto, transportes.
// Merged em ALL_TRIVIA (ver triviaBoost.ts).
import type { TriviaQuestion } from "@/lib/triviaBoost";

const q = (
  category: string,
  age: number,
  prompt: string,
  options: string[],
  answerIndex: number,
  hint?: string,
): TriviaQuestion => ({ category, age, prompt, options, answerIndex, hint });

export const TRIVIA_ULTRA: TriviaQuestion[] = [
  // ═══ ESPAÇO (40) ═══
  q("espaco", 6, "Em que planeta vivemos?", ["Marte", "Terra", "Vénus", "Mercúrio"], 1),
  q(
    "espaco",
    7,
    "Qual é o maior planeta do Sistema Solar?",
    ["Júpiter", "Saturno", "Neptuno", "Terra"],
    0,
  ),
  q("espaco", 7, "Qual é o planeta vermelho?", ["Vénus", "Mercúrio", "Marte", "Urano"], 2),
  q(
    "espaco",
    6,
    "O que é a Lua?",
    ["Uma estrela", "Um planeta", "O satélite natural da Terra", "Uma nuvem"],
    2,
  ),
  q(
    "espaco",
    8,
    "Qual planeta é famoso pelos seus anéis?",
    ["Júpiter", "Saturno", "Marte", "Mercúrio"],
    1,
  ),
  q(
    "espaco",
    7,
    "Qual é a estrela mais próxima da Terra?",
    ["Sol", "Sirius", "Alpha Centauri", "Polar"],
    0,
  ),
  q(
    "espaco",
    8,
    "Como se chama a galáxia onde vivemos?",
    ["Andrómeda", "Via Láctea", "Triângulo", "Sombrero"],
    1,
  ),
  q("espaco", 6, "Quantos planetas tem o Sistema Solar?", ["7", "8", "9", "10"], 1),
  q("espaco", 8, "Que planeta está mais perto do Sol?", ["Vénus", "Terra", "Mercúrio", "Marte"], 2),
  q(
    "espaco",
    7,
    "O que usam os astronautas para ir ao espaço?",
    ["Foguetão", "Barco", "Avião", "Submarino"],
    0,
  ),
  q(
    "espaco",
    9,
    "Quem foi o primeiro homem no espaço?",
    ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Michael Collins"],
    1,
  ),
  q(
    "espaco",
    9,
    "Em que ano o homem pisou a Lua pela primeira vez?",
    ["1959", "1969", "1979", "1989"],
    1,
  ),
  q(
    "espaco",
    8,
    "Como se chama a roupa dos astronautas?",
    ["Fato de banho", "Traje espacial", "Kimono", "Uniforme escolar"],
    1,
  ),
  q("espaco", 7, "O Sol é uma…", ["Planeta", "Estrela", "Lua", "Galáxia"], 1),
  q(
    "espaco",
    8,
    "O que causa o dia e a noite?",
    ["As nuvens", "A rotação da Terra", "A Lua", "O vento"],
    1,
  ),
  q(
    "espaco",
    9,
    "Qual planeta tem o maior vulcão do Sistema Solar (Olympus Mons)?",
    ["Terra", "Vénus", "Marte", "Mercúrio"],
    2,
  ),
  q(
    "espaco",
    8,
    "Como se chama um pedaço de rocha que cai da Terra do espaço?",
    ["Meteoro", "Cometa", "Satélite", "Nebulosa"],
    0,
  ),
  q(
    "espaco",
    9,
    "Que instrumento usa os cientistas para ver as estrelas?",
    ["Microscópio", "Telescópio", "Periscópio", "Estetoscópio"],
    1,
  ),
  q(
    "espaco",
    7,
    "Quantas patas tem… nada! Quantas luas tem Marte?",
    ["0", "1", "2", "4"],
    2,
    "Fobos e Deimos.",
  ),
  q(
    "espaco",
    9,
    "O que é um cometa?",
    [
      "Uma estrela cadente",
      "Uma bola de gelo e poeira que orbita o Sol",
      "Um planeta pequeno",
      "Uma lua distante",
    ],
    1,
  ),
  q(
    "espaco",
    8,
    "Qual é o planeta mais quente?",
    ["Mercúrio", "Vénus", "Marte", "Júpiter"],
    1,
    "O efeito estufa deixa Vénus a ~460 °C.",
  ),
  q(
    "espaco",
    9,
    "Como se chama a personagem que anda no espaço fora da nave?",
    ["Piloto", "Astronauta", "Marinheiro", "Paraquedista"],
    1,
  ),
  q(
    "espaco",
    10,
    "O que mantém os planetas a orbitar o Sol?",
    ["O vento solar", "A gravidade", "O magnetismo", "A luz"],
    1,
  ),
  q(
    "espaco",
    8,
    "A Terra gira em torno de si mesma. Isso chama-se…",
    ["Translação", "Rotação", "Elevação", "Gravitação"],
    1,
  ),
  q(
    "espaco",
    10,
    "A viagem da Terra em volta do Sol chama-se…",
    ["Rotação", "Translação", "Revolução própria", "Oscilação"],
    1,
  ),
  q(
    "espaco",
    7,
    "De que cor é o Sol quando olhamos para ele de manhã?",
    ["Azul", "Amarelo/laranja", "Verde", "Roxo"],
    1,
  ),
  q(
    "espaco",
    9,
    "Qual destes NÃO é um planeta?",
    ["Plutão", "Neptuno", "Saturno", "Urano"],
    0,
    "Plutão é agora um planeta anão.",
  ),
  q(
    "espaco",
    8,
    "O que os astronautas bebem no espaço?",
    ["Só sumo", "Água em sacos com palhinha", "Coca-cola quente", "Leite de coco"],
    1,
  ),
  q(
    "espaco",
    9,
    "O que acontece à água a ferver no espaço?",
    ["Fica parada", "Faz bolhas enormes e flutua", "Congela logo", "Desaparece"],
    1,
  ),
  q(
    "espaco",
    10,
    "Como se chama a estação espacial internacional?",
    ["ISS", "NASA", "SUV", "DNA"],
    0,
  ),
  q(
    "espaco",
    8,
    "Quantos minutos demora a luz do Sol a chegar à Terra?",
    ["8 segundos", "8 minutos", "8 horas", "8 dias"],
    1,
  ),
  q(
    "espaco",
    9,
    "A Lua tem ar para respirar?",
    ["Sim, muito", "Sim, um pouco", "Não, quase nenhum", "Só à noite"],
    2,
  ),
  q(
    "espaco",
    7,
    "O que vemos no céu à noite e que brilha?",
    ["A Lua e as estrelas", "As árvores", "Os carros", "As nuvens escuras"],
    0,
  ),
  q(
    "espaco",
    10,
    "Qual é a maior lua do Sistema Solar?",
    ["A nossa Lua", "Ganimedes (de Júpiter)", "Fobos", "Europa"],
    1,
  ),
  q(
    "espaco",
    8,
    "Os astronautas no espaço sentem-se…",
    ["Mais pesados", "Quase sem peso (gravidade zero)", "Igual à Terra", "Mais leves só de manhã"],
    1,
  ),
  q(
    "espaco",
    9,
    "Que país enviou o primeiro satélite (Sputnik)?",
    ["EUA", "União Soviética", "China", "Brasil"],
    1,
  ),
  q(
    "espaco",
    10,
    "Como se chama o cinto de pedras entre Marte e Júpiter?",
    ["Cinturão de asteroides", "Cinturão de Kuiper", "Círculo de cometas", "Anel de Saturno"],
    0,
  ),
  q(
    "espaco",
    8,
    "O que é uma estrela cadente?",
    [
      "Uma estrela a morrer",
      "Um pedaço de rocha a queimar na atmosfera",
      "Um avião",
      "Um satélite de TV",
    ],
    1,
  ),
  q(
    "espaco",
    9,
    "O telescópio espacial mais famoso chama-se…",
    ["Hubble", "Newton", "Einstein", "Galileu"],
    0,
  ),
  q(
    "espaco",
    10,
    "Em que planeta chove diamante (teoria científica)?",
    ["Neptuno", "Marte", "Terra", "Mercúrio"],
    0,
  ),

  // ═══ CORPO & SAÚDE (35) ═══
  q("corpo", 6, "Quantos olhos temos?", ["1", "2", "3", "4"], 1),
  q("corpo", 6, "O que usamos para ouvir?", ["Nariz", "Orelhas", "Boca", "Mãos"], 1),
  q(
    "corpo",
    7,
    "Quantos dentes de leite tem uma criança (aproximadamente)?",
    ["10", "20", "32", "40"],
    1,
  ),
  q(
    "corpo",
    7,
    "O que faz o coração?",
    ["Bombeia o sangue", "Digere a comida", "Pensa", "Respira"],
    0,
  ),
  q("corpo", 6, "Quantas mãos temos?", ["1", "2", "3", "5"], 1),
  q(
    "corpo",
    7,
    "O que devemos fazer antes de comer?",
    ["Correr", "Lavar as mãos", "Dormir", "Ver TV"],
    1,
  ),
  q("corpo", 8, "Qual é o órgão que respiramos?", ["Estômago", "Pulmões", "Fígado", "Rins"], 1),
  q("corpo", 8, "Quantos dedos têm as duas mãos juntas?", ["8", "10", "12", "20"], 1),
  q("corpo", 6, "Para que servem os pés?", ["Ouvir", "Andar e correr", "Cheirar", "Falar"], 1),
  q(
    "corpo",
    7,
    "O que é bom para os dentes?",
    ["Doces todo o dia", "Escovar 2× ao dia", "Nunca escovar", "Beber refrigerante"],
    1,
  ),
  q("corpo", 8, "O cabelo cresce a partir de…", ["Ponta", "Raiz", "Meio", "Nunca cresce"], 1),
  q("corpo", 7, "Qual é o maior órgão do corpo?", ["Fígado", "Pele", "Coração", "Cérebro"], 1),
  q(
    "corpo",
    9,
    "O que bombeia o sangue para todo o corpo?",
    ["Pulmões", "Coração", "Estômago", "Cérebro"],
    1,
  ),
  q(
    "corpo",
    8,
    "Quantas vezes por dia devemos escovar os dentes?",
    ["Nunca", "1×", "2× ou mais", "10×"],
    2,
  ),
  q("corpo", 6, "O que usamos para cheirar as flores?", ["Nariz", "Olhos", "Orelhas", "Pés"], 0),
  q(
    "corpo",
    9,
    "O cérebro controla…",
    ["Só os braços", "O corpo todo, pensamentos e memória", "Só a fome", "Só o sono"],
    1,
  ),
  q(
    "corpo",
    7,
    "O que ajuda a ter ossos fortes?",
    ["Leite e sol", "Refrigerantes", "Doces", "Chips"],
    0,
  ),
  q(
    "corpo",
    8,
    "O que acontece quando temos febre?",
    ["Temperatura acima do normal", "Fica tudo azul", "Cabelo cai", "Orelhas crescem"],
    0,
  ),
  q(
    "corpo",
    9,
    "Qual destes alimentos é mais saudável?",
    ["Batatas fritas", "Maçã", "Gomas", "Bolachas recheadas"],
    1,
  ),
  q(
    "corpo",
    8,
    "Para que servem as sobrancelhas?",
    ["Proteger os olhos do suor", "Ouvir melhor", "Cheirar", "Nada"],
    0,
  ),
  q(
    "corpo",
    10,
    "Quantos ossos tem (aproximadamente) o corpo adulto?",
    ["106", "206", "506", "1006"],
    1,
  ),
  q(
    "corpo",
    9,
    "O que é o esqueleto?",
    ["Conjunto de ossos do corpo", "Um tipo de músculo", "Órgão digestivo", "Parte do coração"],
    0,
  ),
  q(
    "corpo",
    7,
    "O que devemos fazer ao espirrar?",
    ["Cobrir nariz e boca com o braço", "Espirrar nos amigos", "Gritar", "Nada"],
    0,
  ),
  q(
    "corpo",
    8,
    "A língua serve para…",
    ["Provar sabores e ajudar a falar", "Ouvir", "Ver", "Correr"],
    0,
  ),
  q("corpo", 6, "Quantas pernas temos?", ["1", "2", "3", "4"], 1),
  q(
    "corpo",
    9,
    "O que é o pulso?",
    ["O ritmo do coração nas artérias", "Um osso do pé", "Parte da orelha", "Um dente"],
    0,
  ),
  q(
    "corpo",
    8,
    "Beber água ajuda a…",
    ["Manter o corpo saudável", "Crescer asas", "Mudar de cor", "Nada"],
    0,
  ),
  q("corpo", 7, "Quantos sentidos temos (os principais)?", ["3", "5", "7", "10"], 1),
  q(
    "corpo",
    9,
    "Qual órgão limpa o sangue e produz bile?",
    ["Fígado", "Estômago", "Traqueia", "Laringe"],
    0,
  ),
  q(
    "corpo",
    10,
    "Onde fica o coração?",
    ["No lado esquerdo do peito (um pouco ao centro)", "Na cabeça", "Na barriga", "No joelho"],
    0,
  ),
  q(
    "corpo",
    8,
    "O que são calorias?",
    ["Energia dos alimentos", "Bactérias", "Vitaminas", "Músculos"],
    0,
  ),
  q(
    "corpo",
    9,
    "Dormir bem ajuda a…",
    ["Crescer e memorizar o que aprendemos", "Ficar acordado", "Perder dentes", "Nada"],
    0,
  ),
  q(
    "corpo",
    7,
    "O que devemos fazer após jogar futebol e suar?",
    ["Beber água", "Comer muito sal", "Ficar ao sol", "Tomar refrigerante gelado"],
    0,
  ),
  q(
    "corpo",
    10,
    "O que é a vacina?",
    ["Uma proteção contra doenças", "Um doce", "Um remédio para cabelo", "Um tipo de osso"],
    0,
  ),
  q(
    "corpo",
    8,
    "Quantos minutos devemos lavar as mãos (aprox.)?",
    ["2 segundos", "20 segundos", "20 minutos", "2 horas"],
    1,
  ),

  // ═══ MÚSICA (25) ═══
  q("musica", 6, "Quantas cordas tem uma guitarra (normal)?", ["4", "6", "8", "10"], 1),
  q(
    "musica",
    7,
    "O que usamos para tocar um tambor?",
    ["As mãos ou baquetas", "A boca", "Os pés só", "O nariz"],
    0,
  ),
  q(
    "musica",
    7,
    "Qual destes é um instrumento de sopro?",
    ["Flauta", "Violino", "Tambor", "Piano"],
    0,
  ),
  q(
    "musica",
    8,
    "Como se chama a pessoa que rege uma orquestra?",
    ["Maestro", "Presidente", "Capitão", "Pintor"],
    0,
  ),
  q(
    "musica",
    6,
    "O piano tem teclas…",
    ["Brancas e pretas", "Só azuis", "Verdes e amarelas", "Invisíveis"],
    0,
  ),
  q(
    "musica",
    8,
    "Quantas notas musicais existem (dó, ré, mi…)?",
    ["5", "7", "10", "12 oficiais"],
    1,
  ),
  q(
    "musica",
    7,
    "Qual é o instrumento nacional mais famoso de Moçambique, feito de madeira e sementes?",
    ["Mbira", "Guitarra elétrica", "Piano", "Acordeão"],
    0,
  ),
  q(
    "musica",
    6,
    "Quando cantamos muito alto e desafinado diz-se que…",
    ["Estamos a desafinar", "Somos maestros", "Tocamos flauta", "Dançamos"],
    0,
  ),
  q(
    "musica",
    9,
    "O que é uma orquestra?",
    [
      "Muitos músicos a tocar juntos",
      "Uma banda de futebol",
      "Um coro de cães",
      "Um tipo de dança",
    ],
    0,
  ),
  q("musica", 8, "Qual instrumento tem 88 teclas?", ["Piano", "Flauta", "Trombeta", "Bateria"], 0),
  q(
    "musica",
    7,
    "O que é uma canção de ninar?",
    ["Música calma para dormir", "Música de festa", "Hino de futebol", "Rap"],
    0,
  ),
  q(
    "musica",
    8,
    "Como se chama quem escreve canções?",
    ["Compositor", "Cozinheiro", "Jardineiro", "Enfermeiro"],
    0,
  ),
  q(
    "musica",
    6,
    "Qual destes faz som muito grave (baixo)?",
    ["Tambor grande", "Flauta fina", "Sino pequeno", "Apito"],
    0,
  ),
  q("musica", 9, "O violino toca-se com…", ["Arco", "Baquetas", "Palheta", "Teclas"], 0),
  q(
    "musica",
    8,
    "Qual é o instrumento de metal mais brilhante da orquestra?",
    ["Trompete", "Contrabaixo", "Oboé", "Violoncelo"],
    0,
  ),
  q(
    "musica",
    7,
    "Em Moçambique, dançamos em festas tradicionais como…",
    ["Marrabenta e mapiko", "Ballet clássico", "Breakdance", "Tango"],
    0,
  ),
  q(
    "musica",
    6,
    "O que faz um DJ?",
    ["Toca e mistura música", "Cozinha", "Pinta quadros", "Costura"],
    0,
  ),
  q("musica", 9, "Quantas cordas tem um violoncelo?", ["4", "6", "12", "20"], 0),
  q(
    "musica",
    8,
    "O que é o refrão de uma canção?",
    ["A parte que se repete", "O início", "O final", "O silêncio"],
    0,
  ),
  q(
    "musica",
    7,
    "Qual destes é um instrumento de percussão?",
    ["Xilofone", "Flauta", "Trompa", "Clarinete"],
    0,
  ),
  q(
    "musica",
    6,
    "Quando batemos palmas estamos a fazer…",
    ["Percussão com o corpo", "Sopro", "Cordas", "Pintura"],
    0,
  ),
  q(
    "musica",
    10,
    "Quem compôs 'Ode à Alegria'?",
    ["Beethoven", "Mozart criança", "Elvis", "Shakira"],
    0,
  ),
  q(
    "musica",
    8,
    "O silêncio na música representa-se com…",
    ["Pausa", "Nota alta", "Dó sustenido", "Clave de sol"],
    0,
  ),
  q(
    "musica",
    7,
    "O kalimba/mbira toca-se com…",
    ["Os polegares", "Os pés", "Os cotovelos", "A boca"],
    0,
  ),
  q(
    "musica",
    9,
    "O que é um coral?",
    ["Grupo de pessoas que canta junto", "Peixe colorido", "Tipo de tambor", "Flauta dupla"],
    0,
  ),

  // ═══ INVENTORES & DESCOBERTAS (30) ═══
  q(
    "inventores",
    8,
    "Quem inventou a lâmpada elétrica prática?",
    ["Thomas Edison", "Isaac Newton", "Albert Einstein", "Leonardo da Vinci"],
    0,
  ),
  q(
    "inventores",
    8,
    "Quem inventou o telefone?",
    ["Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Nikola Tesla"],
    0,
  ),
  q(
    "inventores",
    9,
    "Quem inventou o avião (primeiro voo controlado)?",
    ["Irmãos Wright", "Irmãos Grimm", "Irmãos Lumière", "Irmãos Disney"],
    0,
  ),
  q(
    "inventores",
    8,
    "Quem criou a teoria da relatividade?",
    ["Albert Einstein", "Galileu Galilei", "Marie Curie", "Charles Darwin"],
    0,
  ),
  q(
    "inventores",
    9,
    "Quem descobriu a penicilina?",
    ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Jonas Salk"],
    0,
  ),
  q(
    "inventores",
    8,
    "Quem estudou a radiação e ganhou dois Prémios Nobel?",
    ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Grace Hopper"],
    0,
  ),
  q(
    "inventores",
    7,
    "O lápis escreve com…",
    ["Grafite", "Tinta azul", "Carvão de fogo", "Cera de abelha"],
    0,
  ),
  q(
    "inventores",
    8,
    "Quem inventou a imprensa (livros em série)?",
    ["Johannes Gutenberg", "Cristóvão Colombo", "Isaac Newton", "Nikola Tesla"],
    0,
  ),
  q(
    "inventores",
    9,
    "A World Wide Web (web) foi criada por…",
    ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Mark Zuckerberg"],
    0,
  ),
  q(
    "inventores",
    8,
    "O que inventou os Irmãos Lumière?",
    ["Cinema (projetor)", "Helicóptero", "Micro-ondas", "Bicicleta"],
    0,
  ),
  q(
    "inventores",
    9,
    "Quem propôs que a Terra gira em volta do Sol (heliocentrismo)?",
    ["Copérnico", "Ptolomeu", "Aristóteles", "Kepler só"],
    0,
  ),
  q(
    "inventores",
    8,
    "Quem desenhou máquinas voadoras e submarinos há 500 anos?",
    ["Leonardo da Vinci", "Michelangelo", "Picasso", "Van Gogh"],
    0,
  ),
  q(
    "inventores",
    10,
    "Quem descobriu a gravidade ao observar uma maçã cair (conta famosa)?",
    ["Isaac Newton", "Galileu", "Kepler", "Descartes"],
    0,
  ),
  q(
    "inventores",
    8,
    "O para-quedas serve para…",
    ["Cair devagar em segurança", "Voar para cima", "Andar na água", "Cavar buracos"],
    0,
  ),
  q(
    "inventores",
    9,
    "Quem inventou a lâmpada de descarga a LED azul (Nobel 2014)?",
    ["Shuji Nakamura e colegas", "Edison", "Tesla", "Faraday"],
    0,
  ),
  q("inventores", 8, "O papel foi inventado na…", ["China", "Grécia", "Egito", "Índia"], 0),
  q(
    "inventores",
    9,
    "Quem inventou o elevador de segurança?",
    ["Elisha Otis", "James Watt", "Karl Benz", "Rudolf Diesel"],
    0,
  ),
  q(
    "inventores",
    10,
    "O primeiro automóvel a gasolina foi patenteado por…",
    ["Karl Benz", "Henry Ford", "Gottlieb Daimler", "Nicolas Cugnot"],
    0,
  ),
  q("inventores", 8, "A bússola aponta para…", ["O norte", "O sol", "As nuvens", "O chão"], 0),
  q(
    "inventores",
    9,
    "Quem inventou o jogo de vídeo 'Pong' (indústria arcade)?",
    ["Atari (Allan Alcorn)", "Nintendo", "Sega", "Microsoft"],
    0,
  ),
  q(
    "inventores",
    8,
    "Os óculos ajudam pessoas que…",
    ["Vêem mal", "Ouvem pouco", "Falam rápido", "Correm devagar"],
    0,
  ),
  q(
    "inventores",
    10,
    "Quem fez o primeiro transplante cardíaco humano (1967)?",
    ["Christiaan Barnard", "Denton Cooley", "Michael DeBakey", "William Harvey"],
    0,
  ),
  q(
    "inventores",
    9,
    "O micro-ondas foi inventado ao…",
    [
      "Derreter chocolate no bolso perto de radar",
      "Congelar água",
      "Fotografar estrelas",
      "Lavar roupa",
    ],
    0,
  ),
  q(
    "inventores",
    8,
    "Quem inventou o velcro, inspirado em cardos presos no cão?",
    ["George de Mestral", "Levi Strauss", "Nokia", "Adidas"],
    0,
  ),
  q(
    "inventores",
    9,
    "O submarino moderno e a escada telescópica têm invenções de…",
    ["Narcís Monturiol / James Ryan", "Thomas Edison", "Wright", "Bell"],
    0,
  ),
  q(
    "inventores",
    10,
    "Quem criou a primeira programadora da história (algoritmo do computador)?",
    ["Ada Lovelace", "Grace Hopper", "Hedy Lamarr", "Joan Clarke"],
    0,
  ),
  q(
    "inventores",
    8,
    "O telégrafo enviava mensagens usando…",
    ["Código Morse", "Voz gravada", "Fotos", "Vídeo"],
    0,
  ),
  q(
    "inventores",
    9,
    "Quem inventou o processo que tornou o leite seguro (pasteurização)?",
    ["Louis Pasteur", "Jonas Salk", "Alexander Fleming", "Marie Curie"],
    0,
  ),
  q(
    "inventores",
    8,
    "O que permite às lâmpadas LED gastar menos energia?",
    ["Semicondutores que brilham", "Fios de cobre grosso", "Gás nobre quente", "Água"],
    0,
  ),
  q(
    "inventores",
    10,
    "O GPS funciona usando…",
    ["Satélites", "Torres de madeira", "Pombos-correio", "Cabo submarino só"],
    0,
  ),

  // ═══ MOÇAMBIQUE (50) ═══
  q(
    "mocambique",
    6,
    "Qual é a capital de Moçambique?",
    ["Maputo", "Beira", "Nampula", "Quelimane"],
    0,
  ),
  q(
    "mocambique",
    7,
    "Que animal famoso aparece na bandeira de Moçambique?",
    ["Leão", "Akalaka (fuzil AK-47)", "Elefante", "Águia"],
    1,
  ),
  q(
    "mocambique",
    7,
    "Qual é o mar que banha Moçambique?",
    ["Oceano Atlântico", "Oceano Índico", "Mar Vermelho", "Mar da China"],
    1,
  ),
  q("mocambique", 8, "Qual é a moeda de Moçambique?", ["Metical", "Rand", "Dólar", "Kwanza"], 0),
  q(
    "mocambique",
    7,
    "Qual é o maior rio de Moçambique (nasce na África do Sul)?",
    ["Rio Limpopo", "Rio Zambeze", "Rio Save", "Rio Rovuma"],
    1,
    "O Zambeze é o maior da bacia; o Limpopo também atravessa o país.",
  ),
  q(
    "mocambique",
    8,
    "Qual cidade moçambicana é chamada 'Cidade do Açúcar'?",
    ["Maputo", "Xai-Xai", "Marromeu", "Pemba"],
    2,
  ),
  q(
    "mocambique",
    6,
    "A bandeira de Moçambique tem as cores verde, preto, amarelo e…",
    ["Vermelho", "Azul", "Roxo", "Laranja"],
    0,
  ),
  q(
    "mocambique",
    8,
    "O que é a marrabenta?",
    ["Música e dança moçambicana", "Um prato de peixe", "Um jogo de cartas", "Um rio"],
    0,
  ),
  q(
    "mocambique",
    7,
    "Qual é a língua oficial de Moçambique?",
    ["Português", "Inglês", "Francês", "Espanhol"],
    0,
  ),
  q(
    "mocambique",
    8,
    "O capulana é…",
    ["Tecido tradicional colorido", "Uma fruta", "Um tambor", "Um barco"],
    0,
  ),
  q(
    "mocambique",
    7,
    "Qual ilha moçambicana é Património Mundial da UNESCO?",
    ["Ilha de Moçambique", "Ilha da Xefina", "Ilha do Bazaruto", "Ilha de Inhaca"],
    0,
  ),
  q(
    "mocambique",
    9,
    "As Cataratas de Cahora Bassa ficam em que rio?",
    ["Zambeze", "Limpopo", "Incomáti", "Messalo"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Qual é a província mais a norte de Moçambique?",
    ["Cabo Delgado", "Niassa", "Nampula", "Tete"],
    0,
    "Cabo Delgado é a mais a norte; Niassa é a maior em área.",
  ),
  q(
    "mocambique",
    8,
    "O que é a xitende?",
    ["Instrumento de cordas tradicional", "Dança de rua", "Prato de milho", "Jogo de bola"],
    0,
  ),
  q(
    "mocambique",
    7,
    "Qual prato moçambicano leva amendoim, folhas de mandioca e camarão?",
    ["Matapa", "Feijoada", "Couscous", "Sushi"],
    0,
  ),
  q(
    "mocambique",
    6,
    "Qual destes animais vive nos parques de Moçambique?",
    ["Elefante", "Pinguim-imperador", "Panda", "Morsa"],
    0,
  ),
  q(
    "mocambique",
    9,
    "O Arquipélago do Bazaruto é famoso pelos…",
    ["Dugongos e praias", "Neve", "Vulcões ativos", "Florestas de pinheiros"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Qual é a província do carvão e da barragem?",
    ["Tete", "Inhambane", "Gaza", "Sofala"],
    0,
  ),
  q(
    "mocambique",
    7,
    "A cidade de Beira fica em que província?",
    ["Sofala", "Zambezia", "Manica", "Maputo"],
    0,
  ),
  q(
    "mocambique",
    8,
    "O que é o timbila?",
    ["Xilofone tradicional chope", "Tambor de guerra", "Flauta dupla", "Cítara"],
    0,
  ),
  q(
    "mocambique",
    9,
    "A Universidade Eduardo Mondlane fica em…",
    ["Maputo", "Beira", "Nampula", "Lichinga"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Eduardo Mondlane foi…",
    [
      "Herói da independência",
      "Um jogador de futebol",
      "Um rei colonial",
      "Um explorador português",
    ],
    0,
  ),
  q(
    "mocambique",
    7,
    "Em que ano Moçambique ficou independente?",
    ["1965", "1975", "1985", "1995"],
    1,
  ),
  q(
    "mocambique",
    6,
    "Qual fruta é muito popular em Moçambique e cresce nas praias de Inhambane?",
    ["Caju", "Manga", "Coco", "Todas as anteriores"],
    3,
  ),
  q(
    "mocambique",
    8,
    "O Parque Nacional da Gorongosa fica em…",
    ["Sofala", "Cabo Delgado", "Maputo", "Niassa"],
    0,
  ),
  q(
    "mocambique",
    9,
    "Qual província tem a maior reserva natural (Reserva do Niassa)?",
    ["Niassa", "Gaza", "Manica", "Zambézia"],
    0,
  ),
  q(
    "mocambique",
    7,
    "Como se chama o mercado tradicional de rua?",
    ["Mercado municipal", "Feira/mercado do melão", "Shopping", "Centro comercial"],
    1,
  ),
  q(
    "mocambique",
    8,
    "O dia da independência celebra-se a…",
    ["25 de Junho", "7 de Abril", "1 de Maio", "25 de Dezembro"],
    0,
  ),
  q(
    "mocambique",
    9,
    "O 'mapiko' é uma dança de máscaras de qual povo?",
    ["Makonde", "Shangaan", "Macua", "Sena"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Qual cidade do norte é a 'capital do cacau'?",
    ["Nacala", "Pemba", "Angoche", "Ilha de Moçambique"],
    0,
  ),
  q(
    "mocambique",
    7,
    "A província de Gaza tem como capital…",
    ["Xai-Xai", "Chibuto", "Chókwè", "Manjacaze"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Qual é o porto natural mais profundo da África Oriental, em Moçambique?",
    ["Nacala", "Maputo", "Beira", "Quelimane"],
    0,
  ),
  q(
    "mocambique",
    6,
    "O que é um dhow?",
    ["Barco à vela usado no Índico", "Um animal marinho", "Uma dança", "Um tambor"],
    0,
  ),
  q(
    "mocambique",
    9,
    "As pinturas rupestres mais antigas de Moçambique encontram-se em…",
    ["Manica (Chinhamapere)", "Maputo", "Inhambane", "Niassa"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Qual é a montanha mais alta de Moçambique?",
    ["Monte Binga", "Monte Namuli", "Monte Mabu", "Serra da Gorongosa"],
    0,
  ),
  q(
    "mocambique",
    7,
    "Os 'dugongos' são parentes marinhos dos…",
    ["Elefantes (são mamíferos)", "Tubarões", "Crocodilos", "Atuns"],
    0,
  ),
  q(
    "mocambique",
    8,
    "O que é a FRELIMO historicamente?",
    [
      "Movimento da luta pela independência",
      "Uma banda pop",
      "Uma equipa de futebol",
      "Um festival",
    ],
    0,
  ),
  q(
    "mocambique",
    9,
    "Samora Machel foi…",
    [
      "Primeiro presidente de Moçambique",
      "Rei da Zululândia",
      "Governador português",
      "Explorador árabe",
    ],
    0,
  ),
  q(
    "mocambique",
    7,
    "Qual bebida quente moçambicana leva milho torrado e castanha de caju?",
    ["Café de milho (chá de milho)", "Coca", "Leite de soja", "Chá verde"],
    0,
  ),
  q(
    "mocambique",
    8,
    "O festival Kwazoe celebra…",
    ["A cultura jovem moçambicana", "Natal", "Carnaval do Rio", "Independência da Índia"],
    0,
  ),
  q(
    "mocambique",
    6,
    "Os flamingos cor-de-rosa podem ser vistos em…",
    [
      "Baías e salinas moçambicanas",
      "Montes gelados",
      "Florestas de bambu",
      "Savanas secas sem água",
    ],
    0,
  ),
  q(
    "mocambique",
    9,
    "Qual escritora moçambicana ganhou o Prémio Camões?",
    ["Paulina Chiziane", "José Saramago", "Mia Couto é homem", "Lídia Jorge"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Mia Couto é famoso como…",
    ["Escritor moçambicano", "Cantor", "Futebolista", "Piloto"],
    0,
  ),
  q(
    "mocambique",
    7,
    "A Zambézia é famosa pela sua…",
    ["Produção de chá (Gurúè) e cocos", "Neve", "Deserto", "Vulcões"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Como se chama o prato de massa de mandioca que acompanha refeições?",
    ["Xima", "Arroz doce", "Fuba doce", "Cuscuz doce"],
    0,
  ),
  q(
    "mocambique",
    9,
    "O Rio Rovuma separa Moçambique de…",
    ["Tanzânia", "África do Sul", "Zimbábue", "Maláui"],
    0,
  ),
  q(
    "mocambique",
    8,
    "O que é um 'chapa' em Moçambique?",
    ["Minibus de transporte público", "Chapéu tradicional", "Peixe frito", "Jogo de crianças"],
    0,
  ),
  q(
    "mocambique",
    10,
    "A ponte suspensa mais extensa de Moçambique liga…",
    ["Maputo e Catembe", "Beira e Chinde", "Quelimane e Mopeia", "Nacala e Ilha"],
    0,
  ),
  q(
    "mocambique",
    7,
    "O hino de Moçambique chama-se…",
    ["Pátria Amada", "Pátria querida", "Moçambique lindo", "Terra brava"],
    0,
  ),
  q(
    "mocambique",
    8,
    "Os Manganja, Makonde, Macua e Shangaan são…",
    ["Grupos étnicos de Moçambique", "Clubes de futebol", "Bairros de Maputo", "Rios"],
    0,
  ),

  // ═══ LÓGICA & ADIVINHAS (35) ═══
  q(
    "logica",
    6,
    "O que é que tem pés mas não anda?",
    ["Uma mesa", "Um cão", "Um barco à vela (navega)", "Um carro"],
    0,
  ),
  q("logica", 7, "Se tens 3 maçãs e comes 1, quantas ficam?", ["1", "2", "3", "0"], 1),
  q(
    "logica",
    7,
    "O que cresce mas nunca nasce (na árvore)?",
    ["A fruta", "A sombra", "A flor", "A raiz"],
    1,
  ),
  q(
    "logica",
    8,
    "Ana é mais alta que Beto. Beto é mais alto que Carla. Quem é o mais baixo?",
    ["Ana", "Beto", "Carla", "Não sei"],
    2,
  ),
  q(
    "logica",
    6,
    "O que tem dentes mas não morde?",
    ["O pente", "O crocodilo", "O tubarão", "A boca"],
    0,
  ),
  q("logica", 8, "Continua a sequência: 2, 4, 6, 8, …", ["9", "10", "11", "12"], 1),
  q("logica", 9, "Continua: 1, 2, 4, 8, 16, …", ["24", "32", "20", "18"], 1, "Cada número dobra."),
  q(
    "logica",
    7,
    "O que sobe quando a chuva desce?",
    ["O guarda-chuva", "A bota", "O barro", "O rio"],
    0,
  ),
  q(
    "logica",
    6,
    "Qual é mais pesado: 1 kg de algodão ou 1 kg de ferro?",
    ["Ferro", "Algodão", "Pesam igual", "Depende da cor"],
    2,
  ),
  q("logica", 8, "Está de manhã. O sol nasce a que lado?", ["Este", "Oeste", "Norte", "Sul"], 0),
  q(
    "logica",
    9,
    "Numa corrida, ultrapassas o 2.º lugar. Ficas em…",
    ["1.º", "2.º", "3.º", "Último"],
    1,
  ),
  q(
    "logica",
    7,
    "O que é que tem pescoço mas não tem cabeça?",
    ["A garrafa", "A girafa", "A camisa é roupa", "Nada"],
    0,
  ),
  q(
    "logica",
    8,
    "Se hoje é terça-feira, que dia foi ontem?",
    ["Segunda", "Quarta", "Domingo", "Sábado"],
    0,
  ),
  q("logica", 9, "Quantos meses têm 28 dias?", ["1", "12 (todos)", "2", "6"], 1),
  q("logica", 6, "O que tem cabeça mas não pensa?", ["O alho", "O cão", "O menino", "O robô"], 0),
  q(
    "logica",
    8,
    "A mãe de Ana tem 4 filhos: Norte, Sul, Este e…",
    ["Oeste", "Ana", "João", "Maria"],
    1,
  ),
  q(
    "logica",
    10,
    "Numa caixa há 3 meias vermelhas e 3 azuis. No escuro, quantas tiras para teres um par igual?",
    ["2", "3", "4", "6"],
    1,
  ),
  q(
    "logica",
    7,
    "O que fica mais molhado quanto mais lava?",
    ["A água", "A toalha é que seca", "O sabão", "A mão"],
    0,
  ),
  q(
    "logica",
    9,
    "Um relógio marca 15:00. Que horas são no formato de 12?",
    ["3 da tarde", "5 da manhã", "13:00", "15 da noite"],
    0,
  ),
  q("logica", 8, "Qual das palavras NÃO é fruta?", ["Banana", "Laranja", "Cenoura", "Manga"], 2),
  q(
    "logica",
    10,
    "Se 3 gatos apanham 3 ratos em 3 minutos, quantos gatos apanham 100 ratos em 100 minutos?",
    ["3", "100", "33", "10"],
    0,
  ),
  q(
    "logica",
    7,
    "O que é mais comprido: um metro ou um centímetro?",
    ["Centímetro", "Metro", "São iguais", "Depende"],
    1,
  ),
  q(
    "logica",
    9,
    "Todos os pássaros têm asas. O pinguim tem asas. Logo o pinguim…",
    ["É um pássaro", "É um peixe", "É um mamífero", "Não tem asas"],
    0,
  ),
  q(
    "logica",
    8,
    "Escondeste num copo. Que parte do copo fica vazia quando o viras?",
    ["O interior", "A base", "A borda", "Nenhuma"],
    0,
  ),
  q("logica", 6, "Quantos dias tem uma semana?", ["5", "6", "7", "8"], 2),
  q("logica", 9, "O oposto de 'caro' é…", ["Barato", "Caro também", "Duro", "Leve"], 0),
  q(
    "logica",
    8,
    "O que vais encontrar no fim de tudo?",
    ["A letra 'o'", "Nada", "O prémio", "O chão"],
    0,
  ),
  q(
    "logica",
    10,
    "Se eu der 1/2 de uma pizza a cada amigo, 2 pizzas alimentam quantos amigos?",
    ["2", "3", "4", "8"],
    2,
  ),
  q(
    "logica",
    7,
    "Uma casa tem 4 cantos. Um gato senta-se em cada canto. Quantos gatos?",
    ["3", "4", "5", "8"],
    1,
  ),
  q(
    "logica",
    9,
    "Qual número é diferente: 4, 9, 16, 20?",
    ["4", "9", "16", "20"],
    3,
    "Todos são quadrados perfeitos exceto 20.",
  ),
  q(
    "logica",
    8,
    "O que se enche de buracos e continua a guardar água?",
    ["A esponja", "O papel", "A parede", "A rede"],
    0,
  ),
  q("logica", 6, "Que animal diz 'miau'?", ["Cão", "Gato", "Vaca", "Galinha"], 1),
  q("logica", 10, "Metade de metade de 8 é…", ["1", "2", "4", "6"], 1),
  q("logica", 9, "Se rodares a letra N 90 graus parece…", ["Z", "M", "H", "W"], 0),

  // ═══ PLANTAS & NATUREZA (25) ═══
  q(
    "plantas",
    6,
    "O que as plantas precisam para crescer?",
    ["Sol e água", "Chocolates", "Brinquedos", "Rádio"],
    0,
  ),
  q(
    "plantas",
    7,
    "O que libertam as plantas para respirarmos?",
    ["Oxigénio", "Fumo", "Azul", "Areia"],
    0,
  ),
  q("plantas", 8, "Qual parte da planta segura-a no solo?", ["Raiz", "Folha", "Flor", "Fruto"], 0),
  q("plantas", 7, "A mangueira dá…", ["Mangas", "Maçãs", "Bananas", "Morangos"], 0),
  q(
    "plantas",
    8,
    "O que atrai as abelhas às flores?",
    ["Néctar e cores", "O vento", "O barulho", "As pedras"],
    0,
  ),
  q(
    "plantas",
    9,
    "O cacto guarda água porque vive no…",
    ["Deserto", "Polo Norte", "Fundo do mar", "Céu"],
    0,
  ),
  q("plantas", 6, "Qual destas é uma flor?", ["Girassol", "Banana", "Pedra", "Palha"], 0),
  q(
    "plantas",
    8,
    "As folhas verdes fazem a fotossíntese usando…",
    ["Luz solar", "Luz da lua só", "Flash de telemóvel", "Vela"],
    0,
  ),
  q(
    "plantas",
    7,
    "De que árvore vem o coco?",
    ["Cocoteiro/coqueiro", "Pinheiro", "Eucalipto", "Baobá dá coco? Não"],
    0,
  ),
  q(
    "plantas",
    9,
    "O baobá é uma árvore…",
    ["Gigante e grossa de África", "Pequena de interior", "Aquática", "Sem folhas nunca"],
    0,
  ),
  q(
    "plantas",
    8,
    "O que é o tronco?",
    ["Caule forte da árvore", "Raiz profunda", "Flor grande", "Semente pequena"],
    0,
  ),
  q(
    "plantas",
    7,
    "Qual fruta tem espinhos por fora e amarela por dentro?",
    ["Ananás", "Manga", "Melancia", "Papaia"],
    0,
  ),
  q(
    "plantas",
    6,
    "As árvores servem para…",
    ["Dar sombra, frutas e oxigénio", "Nada", "Só lenha", "Só decorar ruas"],
    0,
  ),
  q(
    "plantas",
    9,
    "O que é uma semente?",
    ["O 'bebé' da planta", "Uma flor morta", "Um tipo de folha", "Um ramo seco"],
    0,
  ),
  q(
    "plantas",
    8,
    "Porque caem as folhas no outono (em climas frios)?",
    ["Para poupar energia no frio", "Estão tristes", "Para voar", "Vão nadar"],
    0,
  ),
  q(
    "plantas",
    10,
    "O que é a seiva?",
    ["Líquido que circula na planta", "Pó da flor", "Raiz seca", "Cortiça"],
    0,
  ),
  q(
    "plantas",
    7,
    "A cana-de-açúcar cresce muito em…",
    ["Zambézia (Moçambique)", "Islandia", "Alpes", "Saara central"],
    0,
  ),
  q(
    "plantas",
    8,
    "O arroz cresce melhor em…",
    ["Campos alagados (arrozais)", "Areia seca", "Neve", "Topo de montanhas sem água"],
    0,
  ),
  q("plantas", 6, "Que cor tem a relva?", ["Verde", "Azul", "Rosa", "Preta"], 0),
  q(
    "plantas",
    9,
    "Uma árvore anual que é gigante em savanas e guarda água no tronco é o…",
    ["Baobá (imbondeiro)", "Bonsai", "Salgueiro", "Bétula"],
    0,
  ),
  q(
    "plantas",
    8,
    "As ervas aromáticas como o manjericão servem para…",
    ["Dar sabor à comida", "Lavar roupa", "Construir casas", "Combustível de carros"],
    0,
  ),
  q("plantas", 7, "A flor vira…", ["Fruto (após polinização)", "Pedra", "Pássaro", "Areia"], 0),
  q(
    "plantas",
    8,
    "O que é ovinde (fruto do baobá)?",
    ["Fruto comestível com polpa ácida", "Uma ave", "Um peixe", "Uma raiz doce"],
    0,
  ),
  q(
    "plantas",
    9,
    "A floresta de Mabu em Moçambique é…",
    [
      "Uma das maiores florestas de montanha de África",
      "Um deserto",
      "Um parque urbano",
      "Uma praia",
    ],
    0,
  ),
  q(
    "plantas",
    6,
    "Cortar muitas árvores sem plantar causa…",
    ["Desflorestação", "Mais chuva sempre", "Frio eterno", "Nada"],
    0,
  ),

  // ═══ OCEANO & ÁGUAS (25) ═══
  q(
    "oceano",
    6,
    "Que animal marinho tem tentáculos e parece geleia?",
    ["Água-viva", "Tubarão", "Polvo", "Baleia"],
    0,
  ),
  q(
    "oceano",
    7,
    "O maior animal do mundo é…",
    ["A baleia-azul", "O elefante", "O tubarão-branco", "O polvo-gigante"],
    0,
  ),
  q("oceano", 8, "Quantos braços tem um polvo?", ["6", "8", "10", "12"], 1),
  q(
    "oceano",
    7,
    "O que é um recife de coral?",
    [
      "Cidade construída por animais pequenos",
      "Uma praia de areia",
      "Um barco afundado",
      "Um tipo de onda",
    ],
    0,
  ),
  q(
    "oceano",
    8,
    "Qual destes NÃO é peixe?",
    ["Golfinho", "Sardinha", "Atum", "Sargo"],
    0,
    "O golfinho é um mamífero.",
  ),
  q(
    "oceano",
    9,
    "Como se chama a subida e descida do mar?",
    ["Marés", "Ondas-choque", "Correntes de ar", "Furações"],
    0,
  ),
  q("oceano", 6, "O mar é feito de água…", ["Salgada", "Doce", "Gaseificada", "Congelada toda"], 0),
  q(
    "oceano",
    8,
    "O cavalo-marinho é…",
    ["Um peixe pequeno curioso", "Um mamífero grande", "Um réptil", "Um molusco"],
    0,
  ),
  q(
    "oceano",
    9,
    "Que animal marinho muda de cor para se esconder?",
    ["Polvo/camaleão-do-mar", "Sardinha", "Baleia", "Estrela-do-mar"],
    0,
  ),
  q(
    "oceano",
    7,
    "Os corais são animais ou plantas?",
    ["Animais (pólipos)", "Plantas", "Pedras vivas", "Minerais"],
    0,
  ),
  q(
    "oceano",
    8,
    "A estrela-do-mar tem tipicamente…",
    ["5 braços", "2 braços", "10 patas articuladas", "Sem braços"],
    0,
  ),
  q(
    "oceano",
    9,
    "O que é a maré alta?",
    ["O mar sobe na costa", "O mar desaparece", "Chove mais", "O sol esquenta mais"],
    0,
  ),
  q(
    "oceano",
    10,
    "Qual destes rios é o mais profundo do mundo?",
    ["Rio Congo", "Zambeze", "Nilo", "Limpopo"],
    0,
  ),
  q(
    "oceano",
    7,
    "O que faz as ondas?",
    ["O vento sobre a água", "Os peixes a nadar", "Os barcos", "A lua chora"],
    0,
  ),
  q(
    "oceano",
    8,
    "O camarão, o caranguejo e o lagosta têm…",
    ["Exosqueleto (concha dura)", "Peles macias", "Pelos", "Escamas"],
    0,
  ),
  q(
    "oceano",
    9,
    "As tartarugas-marinhas põem ovos…",
    ["Nas praias de areia", "No fundo do mar", "Em árvores", "Nas rochas do fundo"],
    0,
  ),
  q(
    "oceano",
    8,
    "O que é a água doce?",
    ["Água sem sal (rios, lagos)", "Água congelada", "Água com gás", "Água do mar"],
    0,
  ),
  q(
    "oceano",
    9,
    "Os peixes respiram através de…",
    ["Brânquias", "Pulmões grandes", "Pele só", "Nariz"],
    0,
  ),
  q(
    "oceano",
    10,
    "O ponto mais profundo do oceano é…",
    ["Fossa das Marianas", "Praia de Bilene", "Delta do Save", "Baía de Maputo"],
    0,
  ),
  q("oceano", 6, "Qual destes vive na água?", ["Peixe", "Galinha", "Leão", "Macaco"], 0),
  q(
    "oceano",
    8,
    "Para poupar o mar devemos…",
    ["Não deitar plástico na água", "Pescar tudo", "Lavar carros no rio", "Fogueiras na praia"],
    0,
  ),
  q(
    "oceano",
    7,
    "A sardinha é muito pescada em…",
    ["Maputo e Beira", "Moscos de neve", "Desertos", "Topos de montanha"],
    0,
  ),
  q(
    "oceano",
    9,
    "O dugongo de Moçambique come…",
    ["Ervas marinhas", "Peixes grandes", "Corais", "Conchas"],
    0,
  ),
  q(
    "oceano",
    8,
    "O lago Niassa (Maláui) é famoso pela…",
    [
      "Água doce cristalina e peixes coloridos (ciclídeos)",
      "Água salgada",
      "Neve",
      "Cadeiras de praia só",
    ],
    0,
  ),
  q(
    "oceano",
    10,
    "O plástico no oceano…",
    [
      "Mata animais e entra na comida",
      "Desaparece em 1 dia",
      "Ajuda os corais",
      "Faz peixes felizes",
    ],
    0,
  ),

  // ═══ PROFISSÕES (20) ═══
  q(
    "profissoes",
    6,
    "Quem cuida dos doentes no hospital?",
    ["Enfermeiro", "Cozinheiro", "Motorista", "Pintor"],
    0,
  ),
  q(
    "profissoes",
    6,
    "Quem ensina na escola?",
    ["Professor", "Bombeiro", "Farmacêutico", "Banco"],
    0,
  ),
  q("profissoes", 7, "Quem apaga incêndios?", ["Bombeiro", "Polícia", "Médico", "Jardineiro"], 0),
  q(
    "profissoes",
    7,
    "Quem constrói casas?",
    ["Construtor/pedreiro", "Dentista", "Carteiro", "Advogado"],
    0,
  ),
  q(
    "profissoes",
    8,
    "Quem pilota aviões?",
    ["Piloto", "Capitão de navio", "Maquinista", "Astronauta"],
    0,
  ),
  q(
    "profissoes",
    8,
    "Quem estuda as estrelas?",
    ["Astrónomo", "Astrologo", "Geólogo", "Biólogo marinho"],
    0,
  ),
  q(
    "profissoes",
    9,
    "Quem cura os dentes?",
    ["Dentista", "Oftalmologista", "Pediatra é médico de crianças", "Veterinário"],
    0,
  ),
  q(
    "profissoes",
    8,
    "Quem cuida de animais doentes?",
    ["Veterinário", "Médico de pessoas", "Podólogo", "Barbeiro"],
    0,
  ),
  q(
    "profissoes",
    7,
    "Quem entrega cartas e encomendas?",
    ["Carteiro", "Encanador", "Eletricista", "Pescador"],
    0,
  ),
  q(
    "profissoes",
    9,
    "Quem faz operações no hospital?",
    ["Cirurgião", "Radiologista só", "Recepcionista", "Motorista de ambulância"],
    0,
  ),
  q(
    "profissoes",
    8,
    "Quem defende as pessoas nos tribunais?",
    ["Advogado", "Juiz é quem decide", "Testemunha", "Polícia"],
    0,
  ),
  q(
    "profissoes",
    7,
    "Quem conserta tubagens de água?",
    ["Encanador", "Carpinteiro", "Soldador", "Vidraceiro"],
    0,
  ),
  q(
    "profissoes",
    8,
    "Quem cozinha num restaurante grande?",
    ["Chef", "Garçom serve à mesa", "Gerente", "Limpeza"],
    0,
  ),
  q(
    "profissoes",
    9,
    "Quem escreve notícias?",
    ["Jornalista", "Escritor de contos", "Poeta", "Tradutor"],
    0,
  ),
  q(
    "profissoes",
    8,
    "Quem estuda rochas e vulcões?",
    ["Geólogo", "Meteorologista", "Zoólogo", "Botânico"],
    0,
  ),
  q(
    "profissoes",
    7,
    "Quem cultiva a terra e cria gado?",
    ["Agricultor", "Caçador", "Mineiro", "Marinheiro"],
    0,
  ),
  q(
    "profissoes",
    9,
    "Quem projeta edifícios e pontes?",
    ["Engenheiro/arquiteto", "Pintor de paredes", "Eletricista", "Motorista"],
    0,
  ),
  q("profissoes", 8, "Quem pescam no mar?", ["Pescador", "Ferreiro", "Alfaiate", "Jardineiro"], 0),
  q(
    "profissoes",
    10,
    "Quem estuda o tempo e prevê a chuva?",
    ["Meteorologista", "Astrónomo", "Historiador", "Químico"],
    0,
  ),
  q(
    "profissoes",
    6,
    "Quem corta e costura roupa?",
    ["Alfaiate", "Cobrador", "Soldador", "Encanador"],
    0,
  ),

  // ═══ DESPORTO (20) ═══
  q(
    "desporto",
    6,
    "Quantos jogadores tem uma equipa de futebol em campo?",
    ["5", "11", "9", "7"],
    1,
  ),
  q(
    "desporto",
    7,
    "Quantos minutos dura um jogo de futebol (normal)?",
    ["60", "90", "120", "45"],
    1,
  ),
  q(
    "desporto",
    7,
    "Em que desporto se usa uma bola laranja e cestos?",
    ["Basquetebol", "Futebol", "Andebol", "Ténis"],
    0,
  ),
  q("desporto", 8, "Onde nasceram os Jogos Olímpicos?", ["Grécia", "Egito", "China", "Brasil"], 0),
  q("desporto", 8, "Quantos anéis tem o símbolo olímpico?", ["3", "5", "7", "9"], 1),
  q("desporto", 7, "Com quantos pontos se ganha um 'golo' no futebol?", ["1", "3", "5", "7"], 0),
  q(
    "desporto",
    8,
    "Em que desporto usamos raquete?",
    ["Ténis", "Natação", "Ciclismo", "Atletismo"],
    0,
  ),
  q(
    "desporto",
    9,
    "O Mambas é a seleção nacional de… de Moçambique",
    ["Futebol", "Basquete", "Voleibol", "Andebol"],
    0,
  ),
  q(
    "desporto",
    8,
    "Nadar, correr e pedalar é um…",
    ["Triatlo", "Biopolo", "Duathlon", "Tetratlo"],
    0,
  ),
  q(
    "desporto",
    7,
    "Quantos jogadores tem uma equipa de basquete em campo?",
    ["5", "6", "7", "11"],
    0,
  ),
  q(
    "desporto",
    9,
    "O campeão olímpico corre 100 metros em cerca de…",
    ["10 segundos", "1 minuto", "30 segundos", "5 segundos"],
    0,
  ),
  q(
    "desporto",
    8,
    "Quantos pontos vale um cesto do meio da quadra (basquete)?",
    ["2", "3", "1", "4"],
    0,
  ),
  q(
    "desporto",
    7,
    "Em que desporto se salta com vara?",
    ["Salto com vara (atletismo)", "Futebol", "Boxe", "Vela"],
    0,
  ),
  q(
    "desporto",
    6,
    "Que desporto se joga na água?",
    ["Pólo aquático", "Críquete", "Golfe", "Badminton"],
    0,
  ),
  q(
    "desporto",
    9,
    "Quem é a atleta olímpica campeã de Moçambique (800 m)?",
    ["Maria Mutola", "Eusébio", "Sonny Bil", "Almami Da Silva"],
    0,
  ),
  q(
    "desporto",
    8,
    "Quantos sets vencidos dão o jogo de voleibol (normal)?",
    ["3", "2", "4", "5 sempre"],
    0,
  ),
  q("desporto", 7, "O guarda-redes usa…", ["Luvas", "Chinelos", "Boné", "Óculos"], 0),
  q(
    "desporto",
    8,
    "Em que desporto existe 'fora-de-jogo'?",
    ["Futebol", "Natação", "Ténis de mesa", "Xadrez"],
    0,
  ),
  q(
    "desporto",
    10,
    "Quantos períodos tem um jogo de basquete FIBA?",
    ["4×10 min", "2×45 min", "3×20 min", "1×90 min"],
    0,
  ),
  q(
    "desporto",
    6,
    "Correr, saltar e lançar pertence a…",
    ["Atletismo", "Ginástica rítmica", "Esgrima", "Remo"],
    0,
  ),

  // ═══ TRANSPORTES (15) ═══
  q(
    "transportes",
    6,
    "Que transporte anda nos carris?",
    ["Comboio", "Barco", "Avião", "Bicicleta"],
    0,
  ),
  q(
    "transportes",
    6,
    "O que se usa para voar no céu?",
    ["Avião", "Carro", "Barco", "Camioneta"],
    0,
  ),
  q(
    "transportes",
    7,
    "O transporte aquático mais comum em Moçambique nas praias é…",
    ["Barco/dhow", "Mota só", "Comboio", "Metro"],
    0,
  ),
  q(
    "transportes",
    8,
    "A bicicleta é boa para…",
    ["Saúde e ambiente", "Voar", "Cavar", "Pescar"],
    0,
  ),
  q("transportes", 7, "Quantas rodas tem um carro (normal)?", ["3", "4", "5", "6"], 1),
  q(
    "transportes",
    8,
    "O que move um carro elétrico?",
    ["Baterias e motor elétrico", "Gasolina", "Carvão", "Vela de vento"],
    0,
  ),
  q(
    "transportes",
    9,
    "O metro é…",
    ["Comboio urbano", "Unidade de medida", "Autocarro de praia", "Helicóptero"],
    0,
  ),
  q(
    "transportes",
    7,
    "Para atravessar rios grandes, usamos…",
    ["Ponte ou barco", "Escada", "Túnel só debaixo da terra nunca", "Skate"],
    0,
  ),
  q(
    "transportes",
    8,
    "O helicóptero voa com…",
    ["Hélices no teto", "Asas fixas como avião", "Balões de gás", "Rodas voadoras"],
    0,
  ),
  q(
    "transportes",
    6,
    "O autocarro (chapa grande) serve para…",
    ["Transportar muitas pessoas", "Corridas de cavalo", "Semear milho", "Pescar"],
    0,
  ),
  q(
    "transportes",
    9,
    "O comboio de Maputo liga…",
    ["Maputo a Ressano Garcia (fronteira)", "Paris a Roma", "Peking a Xangai", "Nairobi ao Cairo"],
    0,
  ),
  q(
    "transportes",
    8,
    "A ambulância serve para…",
    ["Levar doentes com urgência", "Entregar pizza", "Passear turistas", "Construir casas"],
    0,
  ),
  q(
    "transportes",
    7,
    "O cavalo é um transporte…",
    ["Tradicional (montado)", "Motorizado", "Aquático", "Aéreo"],
    0,
  ),
  q(
    "transportes",
    10,
    "O aeroporto internacional de Maputo chama-se…",
    ["Maputo International (Matalane)", "Nacala Aeródromo", "Beira Air", "Xai-Xai Strip"],
    0,
  ),
  q(
    "transportes",
    8,
    "Para segurar trânsito seguro, as crianças devem…",
    ["Usar cadeirinha/cinto", "Andar na mala", "Pular janelas", "Correr na estrada"],
    0,
  ),
];
